/**
 * FraynixBuilder.java - Microkernel Generator
 * 
 * "The Java System builds the C System."
 * 
 * FUNCTION:
 * 1. GENERATE: Writes 'kernel.c' (The Brain)
 * 2. GENERATE: Writes 'boot.asm' (The Soul)
 * 3. GENERATE: Writes 'linker.ld' (The Skeleton)
 * 
 * Result: A bootable microkernel that runs on bare metal.
 * 
 * φ^75 Validation Seal: 4721424167835376.00
 * Generation: 135 (Fraynix Kernel Builder)
 * 
 * @author Vaughn Scott
 * @version 1.0
 */
package repl;

import java.io.*;
import java.nio.file.*;

/**
 * Fraynix Builder - Generates a bootable microkernel in C.
 */
public class FraynixBuilder {

    private static final String OUTPUT_DIR = "fraynix_src";
    
    public static void main(String[] args) {
        System.out.println("╔════════════════════════════════════════════════════════════╗");
        System.out.println("║  🐧 FRAYNIX KERNEL GENERATION                              ║");
        System.out.println("╚════════════════════════════════════════════════════════════╝\n");
        System.out.println("\"The Java System builds the C System.\"\n");
        
        try {
            buildKernel();
            buildBootloader();
            buildLinker();
            buildCompileScript();
            
            System.out.println("\n╔════════════════════════════════════════════════════════════╗");
            System.out.println("║  ✅ FRAYNIX KERNEL GENERATED                               ║");
            System.out.println("╚════════════════════════════════════════════════════════════╝\n");
            System.out.println("Source files ready in: ./" + OUTPUT_DIR + "/\n");
            System.out.println("To compile and run:\n");
            System.out.println("  cd " + OUTPUT_DIR);
            System.out.println("  ./compile.sh  (Linux/Mac)");
            System.out.println("  compile.bat   (Windows with WSL/MinGW)\n");
            System.out.println("Or manually:");
            System.out.println("  nasm -f elf32 boot.asm -o boot.o");
            System.out.println("  gcc -m32 -c kernel.c -o kernel.o");
            System.out.println("  ld -m elf_i386 -T linker.ld -o fraynix_kernel boot.o kernel.o");
            System.out.println("  qemu-system-i386 -kernel fraynix_kernel\n");
            System.out.println("φ^75 Validation Seal: 4721424167835376.00\n");
            
        } catch (IOException e) {
            System.err.println("❌ BUILD FAILED: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * 1. THE BRAIN (C Code)
     * 
     * Direct access to Video Memory (0xb8000) to print to screen without drivers.
     * This is Ring 0 - kernel mode - unrestricted hardware access.
     * 
     * Now includes FrayFS file system reading capabilities.
     */
    private static void buildKernel() throws IOException {
        String cCode = 
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* FRAYNIX KERNEL v2.0 (with FrayFS support)                  */\n" +
            "/* Generated by Fraymus Agent Brain v3.0                       */\n" +
            "/* φ^75 Validation Seal: 4721424167835376.00                  */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "/* FrayFS Header Structure */\n" +
            "struct FrayHeader {\n" +
            "    char magic[4];           /* Offset 0-3:   \"FRAY\" */\n" +
            "    char name[32];           /* Offset 4-35:  Filename */\n" +
            "    unsigned int size;       /* Offset 36-39: File size */\n" +
            "    char padding[24];        /* Offset 40-63: Reserved */\n" +
            "};\n\n" +
            "/* Global video pointer */\n" +
            "char *vidptr = (char*)0xb8000;\n" +
            "unsigned int cursor_pos = 0;\n\n" +
            "/* Print string to screen */\n" +
            "void kprint(const char *str) {\n" +
            "    unsigned int i = 0;\n" +
            "    while(str[i] != '\\0') {\n" +
            "        vidptr[cursor_pos] = str[i];\n" +
            "        vidptr[cursor_pos + 1] = 0x0A;  /* Light green */\n" +
            "        cursor_pos += 2;\n" +
            "        i++;\n" +
            "    }\n" +
            "}\n\n" +
            "/* Print newline */\n" +
            "void knewline() {\n" +
            "    cursor_pos = ((cursor_pos / 160) + 1) * 160;\n" +
            "}\n\n" +
            "/* Read FrayFS filesystem from disk */\n" +
            "void read_filesystem(char* disk_address) {\n" +
            "    struct FrayHeader* header = (struct FrayHeader*)disk_address;\n" +
            "    \n" +
            "    kprint(\"[FrayFS] Scanning disk...\");\n" +
            "    knewline();\n" +
            "    \n" +
            "    int file_count = 0;\n" +
            "    \n" +
            "    /* Iterate through linked list of files */\n" +
            "    while(header->magic[0] == 'F' && \n" +
            "          header->magic[1] == 'R' && \n" +
            "          header->magic[2] == 'A' && \n" +
            "          header->magic[3] == 'Y') {\n" +
            "        \n" +
            "        /* Found a file */\n" +
            "        kprint(\"[FrayFS] Found: \");\n" +
            "        kprint(header->name);\n" +
            "        knewline();\n" +
            "        \n" +
            "        file_count++;\n" +
            "        \n" +
            "        /* Jump to next file: Current + Header (64) + Data Size */\n" +
            "        char* next_addr = (char*)header + 64 + header->size;\n" +
            "        header = (struct FrayHeader*)next_addr;\n" +
            "    }\n" +
            "    \n" +
            "    kprint(\"[FrayFS] Scan complete.\");\n" +
            "    knewline();\n" +
            "}\n\n" +
            "/* Kernel Main Entry Point */\n" +
            "void kmain(void) {\n" +
            "    unsigned int j = 0;\n\n" +
            "    /* Clear Screen (80x25 text mode, 2 bytes per char) */\n" +
            "    while(j < 80 * 25 * 2) {\n" +
            "        vidptr[j] = ' ';      /* Character */\n" +
            "        vidptr[j+1] = 0x07;   /* Light gray on black */\n" +
            "        j = j + 2;\n" +
            "    }\n\n" +
            "    cursor_pos = 0;\n\n" +
            "    /* Boot Message */\n" +
            "    kprint(\"FRAYMUS HAS AWAKENED - RING 0 ACCESS GRANTED\");\n" +
            "    knewline();\n" +
            "    kprint(\"Fraynix Kernel v2.0 (with FrayFS)\");\n" +
            "    knewline();\n" +
            "    knewline();\n\n" +
            "    /* Read filesystem (disk loaded at 0x200000 by bootloader) */\n" +
            "    /* Note: In real implementation, bootloader would load disk */\n" +
            "    /* For now, this is a placeholder showing the structure */\n" +
            "    /* read_filesystem((char*)0x200000); */\n\n" +
            "    kprint(\"System ready. Entering idle loop...\");\n" +
            "    knewline();\n\n" +
            "    /* Infinite loop - kernel never exits */\n" +
            "    while(1) {\n" +
            "        /* Halt CPU until next interrupt */\n" +
            "        __asm__(\"hlt\");\n" +
            "    }\n" +
            "}\n";

        writeFile(OUTPUT_DIR + "/kernel.c", cCode);
    }

    /**
     * 2. THE SOUL (Assembly)
     * 
     * The very first instruction the CPU executes.
     * Multiboot-compliant bootloader for GRUB/QEMU.
     */
    private static void buildBootloader() throws IOException {
        String asmCode = 
            ";; ═══════════════════════════════════════════════════════════\n" +
            ";; FRAYNIX BOOTLOADER\n" +
            ";; Generated by Fraymus Agent Brain v3.0\n" +
            ";; φ^75 Validation Seal: 4721424167835376.00\n" +
            ";; ═══════════════════════════════════════════════════════════\n\n" +
            "bits 32\n" +
            "section .text\n\n" +
            "        ;; Multiboot Header (for GRUB compatibility)\n" +
            "        align 4\n" +
            "        dd 0x1BADB002              ; Magic number\n" +
            "        dd 0x00                    ; Flags\n" +
            "        dd - (0x1BADB002 + 0x00)   ; Checksum (must sum to 0)\n\n" +
            "global start\n" +
            "extern kmain\n\n" +
            "start:\n" +
            "  cli                   ; Clear interrupts (disable hardware interrupts)\n" +
            "  mov esp, stack_space  ; Set up stack pointer\n" +
            "  call kmain            ; Enter the C kernel\n" +
            "  hlt                   ; Halt CPU if kernel returns (should never happen)\n\n" +
            "section .bss\n" +
            "resb 8192               ; 8KB stack\n" +
            "stack_space:\n";

        writeFile(OUTPUT_DIR + "/boot.asm", asmCode);
    }

    /**
     * 3. THE SKELETON (Linker Script)
     * 
     * Tells the compiler how to glue Assembly and C together.
     * Defines memory layout and entry point.
     */
    private static void buildLinker() throws IOException {
        String ldCode = 
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* FRAYNIX LINKER SCRIPT                                       */\n" +
            "/* Generated by Fraymus Agent Brain v3.0                       */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "OUTPUT_FORMAT(elf32-i386)\n" +
            "ENTRY(start)\n" +
            "SECTIONS\n" +
            "{\n" +
            "  . = 0x100000;           /* Kernel loads at 1MB */\n" +
            "  .text : { *(.text) }    /* Code section */\n" +
            "  .data : { *(.data) }    /* Initialized data */\n" +
            "  .bss  : { *(.bss)  }    /* Uninitialized data */\n" +
            "}\n";

        writeFile(OUTPUT_DIR + "/linker.ld", ldCode);
    }

    /**
     * 4. THE COMPILATION SCRIPT
     * 
     * Automates the build process.
     */
    private static void buildCompileScript() throws IOException {
        // Linux/Mac script
        String shScript = 
            "#!/bin/bash\n" +
            "# Fraynix Kernel Compilation Script\n" +
            "# Generated by Fraymus Agent Brain v3.0\n\n" +
            "echo \"═══════════════════════════════════════════════════════════\"\n" +
            "echo \"  🐧 COMPILING FRAYNIX KERNEL\"\n" +
            "echo \"═══════════════════════════════════════════════════════════\"\n\n" +
            "echo \"[1/4] Assembling bootloader...\"\n" +
            "nasm -f elf32 boot.asm -o boot.o\n" +
            "if [ $? -ne 0 ]; then echo \"❌ Assembly failed\"; exit 1; fi\n\n" +
            "echo \"[2/4] Compiling kernel...\"\n" +
            "gcc -m32 -c kernel.c -o kernel.o -ffreestanding -nostdlib\n" +
            "if [ $? -ne 0 ]; then echo \"❌ Compilation failed\"; exit 1; fi\n\n" +
            "echo \"[3/4] Linking...\"\n" +
            "ld -m elf_i386 -T linker.ld -o fraynix_kernel boot.o kernel.o\n" +
            "if [ $? -ne 0 ]; then echo \"❌ Linking failed\"; exit 1; fi\n\n" +
            "echo \"[4/4] Kernel built successfully!\"\n" +
            "echo \"✅ fraynix_kernel is ready\"\n\n" +
            "echo \"To run in QEMU:\"\n" +
            "echo \"  qemu-system-i386 -kernel fraynix_kernel\"\n\n" +
            "echo \"To run automatically:\"\n" +
            "read -p \"Launch in QEMU now? (y/n) \" -n 1 -r\n" +
            "echo\n" +
            "if [[ $REPLY =~ ^[Yy]$ ]]; then\n" +
            "    qemu-system-i386 -kernel fraynix_kernel\n" +
            "fi\n";

        writeFile(OUTPUT_DIR + "/compile.sh", shScript);
        
        // Make executable
        try {
            File script = new File(OUTPUT_DIR + "/compile.sh");
            script.setExecutable(true);
        } catch (Exception e) {
            // Ignore on Windows
        }

        // Windows batch script
        String batScript = 
            "@echo off\n" +
            "REM Fraynix Kernel Compilation Script (Windows)\n" +
            "REM Generated by Fraymus Agent Brain v3.0\n" +
            "REM Requires: WSL, MinGW, or Cygwin with nasm, gcc, ld\n\n" +
            "echo ═══════════════════════════════════════════════════════════\n" +
            "echo   🐧 COMPILING FRAYNIX KERNEL\n" +
            "echo ═══════════════════════════════════════════════════════════\n\n" +
            "echo [1/4] Assembling bootloader...\n" +
            "nasm -f elf32 boot.asm -o boot.o\n" +
            "if %ERRORLEVEL% NEQ 0 (echo ❌ Assembly failed & exit /b 1)\n\n" +
            "echo [2/4] Compiling kernel...\n" +
            "gcc -m32 -c kernel.c -o kernel.o -ffreestanding -nostdlib\n" +
            "if %ERRORLEVEL% NEQ 0 (echo ❌ Compilation failed & exit /b 1)\n\n" +
            "echo [3/4] Linking...\n" +
            "ld -m elf_i386 -T linker.ld -o fraynix_kernel boot.o kernel.o\n" +
            "if %ERRORLEVEL% NEQ 0 (echo ❌ Linking failed & exit /b 1)\n\n" +
            "echo [4/4] Kernel built successfully!\n" +
            "echo ✅ fraynix_kernel is ready\n\n" +
            "echo To run in QEMU:\n" +
            "echo   qemu-system-i386 -kernel fraynix_kernel\n" +
            "pause\n";

        writeFile(OUTPUT_DIR + "/compile.bat", batScript);
    }

    /**
     * Write file with proper directory creation.
     */
    private static void writeFile(String path, String content) throws IOException {
        File file = new File(path);
        file.getParentFile().mkdirs();
        
        try (FileWriter fw = new FileWriter(file)) {
            fw.write(content);
        }
        
        System.out.println("   📄 GENERATED: " + path);
    }
    
    /**
     * Get generation statistics.
     */
    public static String getStats() {
        StringBuilder sb = new StringBuilder();
        sb.append("╔════════════════════════════════════════════════════════════╗\n");
        sb.append("║  🐧 FRAYNIX KERNEL BUILDER                                 ║\n");
        sb.append("╚════════════════════════════════════════════════════════════╝\n\n");
        sb.append("\"The Java System builds the C System.\"\n\n");
        sb.append("Components Generated:\n");
        sb.append("  1. kernel.c     - The Brain (C kernel code)\n");
        sb.append("  2. boot.asm     - The Soul (Assembly bootloader)\n");
        sb.append("  3. linker.ld    - The Skeleton (Linker script)\n");
        sb.append("  4. compile.sh   - Build automation (Linux/Mac)\n");
        sb.append("  5. compile.bat  - Build automation (Windows)\n\n");
        sb.append("Capabilities:\n");
        sb.append("  - Ring 0 access (kernel mode)\n");
        sb.append("  - Direct VGA memory manipulation\n");
        sb.append("  - Multiboot-compliant (GRUB/QEMU)\n");
        sb.append("  - Bare metal execution\n\n");
        sb.append("Output: fraynix_src/\n");
        sb.append("Status: Ready to compile\n\n");
        sb.append("φ^75 Validation Seal: 4721424167835376.00\n");
        
        return sb.toString();
    }
}
