/**
 * FrayDesktopBuilder.java - Desktop Environment Generator
 * 
 * "The Interface is the System."
 * 
 * FUNCTION:
 * 1. COMPOSITOR: Draws windows with shadows and title bars
 * 2. MOUSE: Renders cursor and tracks X/Y position
 * 3. EVENTS: Click handlers for icons and windows
 * 4. THEME: Gold & Obsidian (The Fraymus Style)
 * 
 * This creates a complete desktop environment with window manager.
 * 
 * φ^75 Validation Seal: 4721424167835376.00
 * Generation: 148 (FrayDesktop - Window Manager)
 * 
 * @author Vaughn Scott
 * @version 1.0
 */
package repl;

import java.io.*;

/**
 * FrayDesktop Builder - Generates desktop environment and window manager.
 */
public class FrayDesktopBuilder {

    private static final String OUTPUT_DIR = "fraynix_src";

    public static void main(String[] args) {
        System.out.println("╔════════════════════════════════════════════════════════════╗");
        System.out.println("║  🖥️ FRAYDESKTOP ENVIRONMENT                                ║");
        System.out.println("╚════════════════════════════════════════════════════════════╝\n");
        System.out.println("\"The Interface is the System.\"\n");
        
        try {
            buildGUIEngine();
            
            System.out.println("\n╔════════════════════════════════════════════════════════════╗");
            System.out.println("║  ✅ FRAYDESKTOP ONLINE - GUI READY                         ║");
            System.out.println("╚════════════════════════════════════════════════════════════╝\n");
            System.out.println("Components generated:");
            System.out.println("  🖥️  gui.c - Desktop environment");
            System.out.println("  🖱️  Mouse driver (PS/2)");
            System.out.println("  🪟 Window compositor");
            System.out.println("  🎨 Theme engine (Gold & Obsidian)");
            System.out.println("  📱 Icon system");
            System.out.println("  🎯 Event handlers\n");
            System.out.println("Theme: Cyber-Gold");
            System.out.println("  Background: Deep Blue");
            System.out.println("  Windows: Obsidian with Gold title bars");
            System.out.println("  Taskbar: Silver with Gold start button");
            System.out.println("  Shadows: Drop shadows for depth\n");
            System.out.println("Applications:");
            System.out.println("  🟥 DOOM - Launch 3D FPS game");
            System.out.println("  🟩 NET - Network broadcasting");
            System.out.println("  ⬜ CODE - FrayC Compiler\n");
            System.out.println("φ^75 Validation Seal: 4721424167835376.00\n");
            
        } catch (IOException e) {
            System.err.println("❌ GUI FAILURE: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Build desktop environment and window manager.
     */
    private static void buildGUIEngine() throws IOException {
        System.out.println("⚡ BOOTING FRAYMUS DESKTOP ENVIRONMENT...\n");
        
        String cCode = 
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* FRAY-GUI: THE WINDOW MANAGER                                */\n" +
            "/* Style: Cyber-Gold (Black, Gold, Glass)                      */\n" +
            "/* Generated by Fraymus Agent Brain v3.0                       */\n" +
            "/* φ^75 Validation Seal: 4721424167835376.00                  */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* MOUSE DRIVER (PS/2)                                          */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "/* Mouse state */\n" +
            "int mouse_x = 160;\n" +
            "int mouse_y = 100;\n" +
            "int mouse_buttons = 0;  /* Bit 0: Left, Bit 1: Right, Bit 2: Middle */\n" +
            "int mouse_byte_cycle = 0;\n" +
            "unsigned char mouse_bytes[3];\n\n" +
            
            "/* Initialize PS/2 mouse */\n" +
            "void init_mouse() {\n" +
            "    /* Enable auxiliary device */\n" +
            "    outb(0x64, 0xA8);\n" +
            "    \n" +
            "    /* Enable interrupts */\n" +
            "    outb(0x64, 0x20);\n" +
            "    unsigned char status = inb(0x60) | 2;\n" +
            "    outb(0x64, 0x60);\n" +
            "    outb(0x60, status);\n" +
            "    \n" +
            "    /* Set defaults */\n" +
            "    outb(0x64, 0xD4);\n" +
            "    outb(0x60, 0xF6);\n" +
            "    inb(0x60);  /* Acknowledge */\n" +
            "    \n" +
            "    /* Enable data reporting */\n" +
            "    outb(0x64, 0xD4);\n" +
            "    outb(0x60, 0xF4);\n" +
            "    inb(0x60);  /* Acknowledge */\n" +
            "    \n" +
            "    kprint(\"[FrayGUI] Mouse initialized\\n\");\n" +
            "}\n\n" +
            
            "/* Handle mouse interrupt (IRQ 12) */\n" +
            "void handle_mouse_interrupt() {\n" +
            "    unsigned char status = inb(0x64);\n" +
            "    if(!(status & 1)) return;\n" +
            "    \n" +
            "    unsigned char val = inb(0x60);\n" +
            "    \n" +
            "    /* PS/2 mouse sends 3-byte packets */\n" +
            "    mouse_bytes[mouse_byte_cycle++] = val;\n" +
            "    \n" +
            "    if(mouse_byte_cycle == 3) {\n" +
            "        mouse_byte_cycle = 0;\n" +
            "        \n" +
            "        /* Parse packet */\n" +
            "        mouse_buttons = mouse_bytes[0] & 0x07;\n" +
            "        \n" +
            "        /* X movement (signed) */\n" +
            "        int dx = mouse_bytes[1];\n" +
            "        if(mouse_bytes[0] & 0x10) dx |= 0xFFFFFF00;  /* Sign extend */\n" +
            "        \n" +
            "        /* Y movement (signed, inverted) */\n" +
            "        int dy = mouse_bytes[2];\n" +
            "        if(mouse_bytes[0] & 0x20) dy |= 0xFFFFFF00;  /* Sign extend */\n" +
            "        \n" +
            "        /* Update position */\n" +
            "        mouse_x += dx;\n" +
            "        mouse_y -= dy;  /* Invert Y */\n" +
            "        \n" +
            "        /* Clamp to screen */\n" +
            "        if(mouse_x < 0) mouse_x = 0;\n" +
            "        if(mouse_x > 319) mouse_x = 319;\n" +
            "        if(mouse_y < 0) mouse_y = 0;\n" +
            "        if(mouse_y > 199) mouse_y = 199;\n" +
            "    }\n" +
            "}\n\n" +
            
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* THEME ENGINE (Cyber-Gold)                                    */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "/* Color palette */\n" +
            "#define COLOR_BLACK     0\n" +
            "#define COLOR_BLUE      1\n" +
            "#define COLOR_GREEN     2\n" +
            "#define COLOR_RED       4\n" +
            "#define COLOR_GOLD      14\n" +
            "#define COLOR_WHITE     15\n" +
            "#define COLOR_OBSIDIAN  8   /* Dark gray */\n" +
            "#define COLOR_SILVER    7   /* Light gray */\n\n" +
            
            "/* Draw window with title bar and shadow */\n" +
            "void draw_window(int x, int y, int w, int h, const char* title) {\n" +
            "    /* 1. Drop shadow (offset 2 pixels) */\n" +
            "    draw_rect(x + 2, y + 2, w, h, COLOR_BLACK);\n" +
            "    \n" +
            "    /* 2. Window body (obsidian) */\n" +
            "    draw_rect(x, y, w, h, COLOR_OBSIDIAN);\n" +
            "    \n" +
            "    /* 3. Title bar (gold) */\n" +
            "    draw_rect(x, y, w, 12, COLOR_GOLD);\n" +
            "    \n" +
            "    /* 4. Title text (would render font here) */\n" +
            "    /* draw_string(x + 4, y + 2, title, COLOR_BLACK); */\n" +
            "    \n" +
            "    /* 5. Close button [X] (red) */\n" +
            "    draw_rect(x + w - 10, y + 2, 8, 8, COLOR_RED);\n" +
            "    \n" +
            "    /* 6. Window border (lighter) */\n" +
            "    draw_hline(x, x + w - 1, y, COLOR_SILVER);\n" +
            "    draw_vline(x, y, y + h - 1, COLOR_SILVER);\n" +
            "    draw_hline(x, x + w - 1, y + h - 1, COLOR_SILVER);\n" +
            "    draw_vline(x + w - 1, y, y + h - 1, COLOR_SILVER);\n" +
            "}\n\n" +
            
            "/* Draw desktop icon */\n" +
            "void draw_icon(int x, int y, const char* name, unsigned char color) {\n" +
            "    /* Icon background */\n" +
            "    draw_rect(x, y, 32, 32, color);\n" +
            "    \n" +
            "    /* Icon border */\n" +
            "    draw_rect(x, y, 32, 32, COLOR_WHITE);  /* Would be hollow rect */\n" +
            "    \n" +
            "    /* Label (would render text below icon) */\n" +
            "    /* draw_string(x, y + 34, name, COLOR_WHITE); */\n" +
            "}\n\n" +
            
            "/* Draw mouse cursor */\n" +
            "void draw_cursor() {\n" +
            "    /* Simple arrow cursor (5x5) */\n" +
            "    put_pixel(mouse_x, mouse_y, COLOR_WHITE);\n" +
            "    put_pixel(mouse_x + 1, mouse_y + 1, COLOR_WHITE);\n" +
            "    put_pixel(mouse_x + 2, mouse_y + 2, COLOR_WHITE);\n" +
            "    put_pixel(mouse_x + 3, mouse_y + 3, COLOR_WHITE);\n" +
            "    put_pixel(mouse_x, mouse_y + 1, COLOR_WHITE);\n" +
            "    put_pixel(mouse_x, mouse_y + 2, COLOR_WHITE);\n" +
            "    put_pixel(mouse_x + 1, mouse_y + 2, COLOR_WHITE);\n" +
            "}\n\n" +
            
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* EVENT SYSTEM                                                 */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "/* Check if point is inside rectangle */\n" +
            "int point_in_rect(int px, int py, int rx, int ry, int rw, int rh) {\n" +
            "    return (px >= rx && px < rx + rw && py >= ry && py < ry + rh);\n" +
            "}\n\n" +
            
            "/* Icon positions */\n" +
            "#define ICON_DOOM_X  20\n" +
            "#define ICON_DOOM_Y  20\n" +
            "#define ICON_NET_X   20\n" +
            "#define ICON_NET_Y   60\n" +
            "#define ICON_CODE_X  20\n" +
            "#define ICON_CODE_Y  100\n" +
            "#define ICON_SIZE    32\n\n" +
            
            "/* Handle click events */\n" +
            "void handle_click() {\n" +
            "    /* Check if DOOM icon clicked */\n" +
            "    if(point_in_rect(mouse_x, mouse_y, ICON_DOOM_X, ICON_DOOM_Y, ICON_SIZE, ICON_SIZE)) {\n" +
            "        kprint(\"[FrayGUI] Launching DOOM...\\n\");\n" +
            "        doom_loop();  /* Launch game */\n" +
            "        return;\n" +
            "    }\n" +
            "    \n" +
            "    /* Check if NET icon clicked */\n" +
            "    if(point_in_rect(mouse_x, mouse_y, ICON_NET_X, ICON_NET_Y, ICON_SIZE, ICON_SIZE)) {\n" +
            "        kprint(\"[FrayGUI] Opening Network Monitor...\\n\");\n" +
            "        /* Would open network app */\n" +
            "        return;\n" +
            "    }\n" +
            "    \n" +
            "    /* Check if CODE icon clicked */\n" +
            "    if(point_in_rect(mouse_x, mouse_y, ICON_CODE_X, ICON_CODE_Y, ICON_SIZE, ICON_SIZE)) {\n" +
            "        kprint(\"[FrayGUI] Opening FrayC Compiler...\\n\");\n" +
            "        /* Would open compiler window */\n" +
            "        return;\n" +
            "    }\n" +
            "}\n\n" +
            
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* DESKTOP MAIN LOOP                                            */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "void start_desktop() {\n" +
            "    /* Initialize subsystems */\n" +
            "    init_vga();\n" +
            "    init_mouse();\n" +
            "    \n" +
            "    kprint(\"[FrayGUI] Desktop environment started\\n\");\n" +
            "    kprint(\"[FrayGUI] Theme: Cyber-Gold\\n\");\n" +
            "    \n" +
            "    int last_buttons = 0;\n" +
            "    \n" +
            "    while(1) {\n" +
            "        /* 1. DRAW BACKGROUND (Wallpaper) */\n" +
            "        draw_rect(0, 0, 320, 200, COLOR_BLUE);  /* Deep blue */\n" +
            "        \n" +
            "        /* 2. DRAW TASKBAR (Bottom) */\n" +
            "        draw_rect(0, 185, 320, 15, COLOR_SILVER);\n" +
            "        \n" +
            "        /* Start button (Gold) */\n" +
            "        draw_rect(2, 187, 50, 11, COLOR_GOLD);\n" +
            "        \n" +
            "        /* System tray area */\n" +
            "        draw_rect(270, 187, 48, 11, COLOR_OBSIDIAN);\n" +
            "        \n" +
            "        /* 3. DRAW DESKTOP ICONS */\n" +
            "        draw_icon(ICON_DOOM_X, ICON_DOOM_Y, \"DOOM\", COLOR_RED);\n" +
            "        draw_icon(ICON_NET_X, ICON_NET_Y, \"NET\", COLOR_GREEN);\n" +
            "        draw_icon(ICON_CODE_X, ICON_CODE_Y, \"CODE\", COLOR_WHITE);\n" +
            "        \n" +
            "        /* 4. DRAW ACTIVE WINDOWS */\n" +
            "        /* Example: Terminal window */\n" +
            "        draw_window(80, 40, 160, 120, \"FrayTerminal\");\n" +
            "        \n" +
            "        /* Window content area */\n" +
            "        draw_rect(82, 54, 156, 104, COLOR_BLACK);\n" +
            "        \n" +
            "        /* 5. UPDATE MOUSE */\n" +
            "        handle_mouse_interrupt();\n" +
            "        \n" +
            "        /* 6. HANDLE CLICKS */\n" +
            "        if((mouse_buttons & 1) && !(last_buttons & 1)) {\n" +
            "            /* Left button pressed (rising edge) */\n" +
            "            handle_click();\n" +
            "        }\n" +
            "        last_buttons = mouse_buttons;\n" +
            "        \n" +
            "        /* 7. DRAW CURSOR (Always on top) */\n" +
            "        draw_cursor();\n" +
            "        \n" +
            "        /* Frame delay */\n" +
            "        for(volatile int i = 0; i < 50000; i++);\n" +
            "    }\n" +
            "}\n\n" +
            
            "/* Launch desktop from kernel */\n" +
            "void gui_init() {\n" +
            "    kprint(\"[FrayGUI] Initializing desktop environment...\\n\");\n" +
            "    start_desktop();\n" +
            "}\n";

        writeFile(OUTPUT_DIR + "/gui.c", cCode);
        System.out.println("   📄 GENERATED: " + OUTPUT_DIR + "/gui.c");
    }
    
    /**
     * Write file with proper directory creation.
     */
    private static void writeFile(String path, String content) throws IOException {
        File file = new File(path);
        file.getParentFile().mkdirs();
        
        try (FileWriter fw = new FileWriter(file)) {
            fw.write(content);
        }
    }
    
    /**
     * Get desktop statistics.
     */
    public static String getStats() {
        StringBuilder sb = new StringBuilder();
        sb.append("╔════════════════════════════════════════════════════════════╗\n");
        sb.append("║  🖥️ FRAYDESKTOP - WINDOW MANAGER                           ║\n");
        sb.append("╚════════════════════════════════════════════════════════════╝\n\n");
        sb.append("\"The Interface is the System.\"\n\n");
        sb.append("Components:\n");
        sb.append("  - Window compositor\n");
        sb.append("  - PS/2 mouse driver\n");
        sb.append("  - Event system\n");
        sb.append("  - Theme engine\n");
        sb.append("  - Icon manager\n\n");
        sb.append("Theme: Cyber-Gold\n");
        sb.append("  Background: Deep Blue (#0000AA)\n");
        sb.append("  Windows: Obsidian (#555555) with Gold (#FFAA00) title bars\n");
        sb.append("  Taskbar: Silver (#AAAAAA) with Gold start button\n");
        sb.append("  Shadows: 2px offset drop shadows\n\n");
        sb.append("Features:\n");
        sb.append("  - Floating windows with title bars\n");
        sb.append("  - Mouse cursor rendering\n");
        sb.append("  - Click detection\n");
        sb.append("  - Desktop icons\n");
        sb.append("  - Taskbar with start button\n\n");
        sb.append("Applications:\n");
        sb.append("  🟥 DOOM - Launch 3D FPS game\n");
        sb.append("  🟩 NET - Network monitoring\n");
        sb.append("  ⬜ CODE - FrayC Compiler\n\n");
        sb.append("φ^75 Validation Seal: 4721424167835376.00\n");
        
        return sb.toString();
    }
}
