/**
 * FrayExplorerBuilder.java - File Explorer Generator
 * 
 * "The Lens through which we view the Memory."
 * 
 * Generates explorer.c - A visual file manager for FrayFS.
 * 
 * Features:
 * - Parses system.img binary disk image
 * - Displays files with type-specific icons
 * - Interactive navigation (arrow keys)
 * - File operations (open, delete)
 * - Executes .bin files, displays .txt files
 * 
 * φ^75 Validation Seal: 4721424167835376.00
 * Generation: 165 (FrayExplorer - File Manager)
 * 
 * @author Vaughn Scott
 * @version 1.0
 */
package repl;

import java.io.FileWriter;
import java.io.IOException;

/**
 * 📂 FRAY EXPLORER BUILDER
 * Generates the visual file manager for Fraynix OS.
 */
public class FrayExplorerBuilder {

    public static void main(String[] args) {
        System.out.println("╔════════════════════════════════════════════════════════════╗");
        System.out.println("║  📂 FRAY-EXPLORER BUILDER                                  ║");
        System.out.println("╚════════════════════════════════════════════════════════════╝\n");
        System.out.println("\"The Lens through which we view the Memory.\"\n");
        System.out.println("⚡ INSTALLING FILE EXPLORER...\n");
        
        try {
            buildExplorer();
            
            System.out.println("╔════════════════════════════════════════════════════════════╗");
            System.out.println("║  ✅ FRAY-EXPLORER INSTALLED                                ║");
            System.out.println("╚════════════════════════════════════════════════════════════╝\n");
            
            System.out.println("Components generated:");
            System.out.println("  📂 explorer.c - Visual file manager");
            System.out.println("  🔍 FrayFS parser");
            System.out.println("  🎨 Icon renderer");
            System.out.println("  ⌨️  Keyboard navigation");
            System.out.println("  🗑️  File deletion\n");
            
            System.out.println("Features:");
            System.out.println("  - Scans system.img in RAM");
            System.out.println("  - Displays up to 64 files");
            System.out.println("  - Type detection (.bin, .txt)");
            System.out.println("  - Execute binaries on Enter");
            System.out.println("  - View text files");
            System.out.println("  - Delete with 'D' key\n");
            
            System.out.println("Usage:");
            System.out.println("  fray> explore");
            System.out.println("  [W/S] Navigate  [ENTER] Open  [D] Delete  [ESC] Exit\n");
            
            System.out.println("φ^75 Validation Seal: 4721424167835376.00\n");
            
        } catch (IOException e) {
            System.err.println("❌ INSTALL FAILED: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static void buildExplorer() throws IOException {
        String cCode = 
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* FRAY-EXPLORER: VISUAL FILE MANAGER                          */\n" +
            "/* Reads FrayFS headers directly from Memory                   */\n" +
            "/* Generated by Fraymus Agent Brain v3.0                       */\n" +
            "/* φ^75 Validation Seal: 4721424167835376.00                  */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* DATA STRUCTURES                                              */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            
            "struct FileEntry {\n" +
            "    char name[32];\n" +
            "    int size;\n" +
            "    char* data_ptr;\n" +
            "    int active; /* 1=Exists, 0=Deleted */\n" +
            "};\n\n" +

            "struct FileEntry files[64]; /* Cache up to 64 files */\n" +
            "int file_count = 0;\n" +
            "int selected_idx = 0;\n" +
            "char* fs_base = (char*)0x200000; /* Where system.img is loaded */\n\n" +

            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* FILESYSTEM PARSER                                            */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            
            "/* Scan disk image and populate file cache */\n" +
            "void scan_disk() {\n" +
            "    file_count = 0;\n" +
            "    char* ptr = fs_base;\n" +
            "    \n" +
            "    while(ptr[0] == 'F' && ptr[1] == 'R' && ptr[2] == 'A' && ptr[3] == 'Y') {\n" +
            "        /* Found FrayFS Header */\n" +
            "        struct FileEntry* f = &files[file_count];\n" +
            "        \n" +
            "        /* Copy Name (32 bytes at offset 4) */\n" +
            "        for(int i=0; i<32; i++) f->name[i] = ptr[4+i];\n" +
            "        \n" +
            "        /* Read Size (Big Endian, 4 bytes at offset 36) */\n" +
            "        unsigned char* size_bytes = (unsigned char*)(ptr + 36);\n" +
            "        f->size = (size_bytes[0]<<24) | (size_bytes[1]<<16) | (size_bytes[2]<<8) | size_bytes[3];\n" +
            "        \n" +
            "        f->data_ptr = ptr + 64; /* Data starts after 64-byte header */\n" +
            "        f->active = 1;\n" +
            "        \n" +
            "        file_count++;\n" +
            "        if(file_count >= 64) break; /* Cache limit */\n" +
            "        \n" +
            "        /* Jump to next file */\n" +
            "        ptr += (64 + f->size);\n" +
            "    }\n" +
            "}\n\n" +

            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* STRING UTILITIES                                             */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            
            "/* Check if string ends with suffix */\n" +
            "int str_ends_with(const char* str, const char* suffix) {\n" +
            "    int str_len = 0;\n" +
            "    int suf_len = 0;\n" +
            "    \n" +
            "    while(str[str_len] != '\\0') str_len++;\n" +
            "    while(suffix[suf_len] != '\\0') suf_len++;\n" +
            "    \n" +
            "    if(suf_len > str_len) return 0;\n" +
            "    \n" +
            "    for(int i=0; i<suf_len; i++) {\n" +
            "        if(str[str_len - suf_len + i] != suffix[i]) return 0;\n" +
            "    }\n" +
            "    \n" +
            "    return 1;\n" +
            "}\n\n" +

            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* FILE OPERATIONS                                              */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            
            "/* Delete file (mark as inactive) */\n" +
            "void delete_file(int idx) {\n" +
            "    if(idx < 0 || idx >= file_count) return;\n" +
            "    \n" +
            "    /* Mark as deleted */\n" +
            "    files[idx].active = 0;\n" +
            "    \n" +
            "    kprint(\"[FS] FILE DELETED: \");\n" +
            "    kprint(files[idx].name);\n" +
            "    kprint(\"\\n\");\n" +
            "}\n\n" +

            "/* Open/Execute file based on type */\n" +
            "void open_file(int idx) {\n" +
            "    if(idx < 0 || idx >= file_count) return;\n" +
            "    if(files[idx].active == 0) return;\n" +
            "    \n" +
            "    struct FileEntry* f = &files[idx];\n" +
            "    \n" +
            "    kprint(\"[OS] OPENING: \");\n" +
            "    kprint(f->name);\n" +
            "    kprint(\"\\n\");\n" +
            "    \n" +
            "    /* Check file extension */\n" +
            "    if (str_ends_with(f->name, \".bin\")) {\n" +
            "        /* Execute binary */\n" +
            "        kprint(\"[OS] EXECUTING BINARY...\\n\");\n" +
            "        void (*prog)() = (void (*)())f->data_ptr;\n" +
            "        prog();\n" +
            "    }\n" +
            "    else if (str_ends_with(f->name, \".txt\")) {\n" +
            "        /* Display text file */\n" +
            "        kprint(\"[OS] OPENING DOCUMENT...\\n\");\n" +
            "        kprint(\"--- BEGIN FILE ---\\n\");\n" +
            "        \n" +
            "        /* Print file contents */\n" +
            "        for(int i=0; i<f->size && i<1024; i++) {\n" +
            "            char c = f->data_ptr[i];\n" +
            "            if(c == '\\0') break;\n" +
            "            /* Print character */\n" +
            "            char buf[2] = {c, '\\0'};\n" +
            "            kprint(buf);\n" +
            "        }\n" +
            "        \n" +
            "        kprint(\"\\n--- END FILE ---\\n\");\n" +
            "        kprint(\"Press any key to continue...\\n\");\n" +
            "        get_char();\n" +
            "    }\n" +
            "    else {\n" +
            "        kprint(\"[OS] UNKNOWN FILE TYPE\\n\");\n" +
            "    }\n" +
            "}\n\n" +

            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* UI RENDERER                                                  */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            
            "/* Draw file explorer window */\n" +
            "void draw_explorer() {\n" +
            "    /* Clear screen */\n" +
            "    clear_screen();\n" +
            "    \n" +
            "    /* Title */\n" +
            "    kprint(\"╔════════════════════════════════════════════════════════════╗\\n\");\n" +
            "    kprint(\"║  📂 FRAY FILES EXPLORER                                    ║\\n\");\n" +
            "    kprint(\"╚════════════════════════════════════════════════════════════╝\\n\\n\");\n" +
            "    \n" +
            "    /* File list */\n" +
            "    int active_count = 0;\n" +
            "    for(int i=0; i<file_count; i++) {\n" +
            "        if(files[i].active == 0) continue;\n" +
            "        \n" +
            "        /* Selection indicator */\n" +
            "        if(i == selected_idx) {\n" +
            "            kprint(\"  ► \"); /* Selection arrow */\n" +
            "        } else {\n" +
            "            kprint(\"    \");\n" +
            "        }\n" +
            "        \n" +
            "        /* Icon based on file type */\n" +
            "        if (str_ends_with(files[i].name, \".txt\")) {\n" +
            "            kprint(\"📄 \"); /* Document icon */\n" +
            "        }\n" +
            "        else if (str_ends_with(files[i].name, \".bin\")) {\n" +
            "            kprint(\"⚙️  \"); /* Executable icon */\n" +
            "        }\n" +
            "        else {\n" +
            "            kprint(\"📦 \"); /* Generic file icon */\n" +
            "        }\n" +
            "        \n" +
            "        /* File name */\n" +
            "        kprint(files[i].name);\n" +
            "        \n" +
            "        /* File size */\n" +
            "        kprint(\" (\");\n" +
            "        print_int(files[i].size);\n" +
            "        kprint(\" bytes)\\n\");\n" +
            "        \n" +
            "        active_count++;\n" +
            "    }\n" +
            "    \n" +
            "    if(active_count == 0) {\n" +
            "        kprint(\"  (No files found)\\n\");\n" +
            "    }\n" +
            "    \n" +
            "    /* Status bar */\n" +
            "    kprint(\"\\n────────────────────────────────────────────────────────────\\n\");\n" +
            "    kprint(\"[W/S] Navigate  [ENTER] Open  [D] Delete  [ESC] Exit\\n\");\n" +
            "    kprint(\"Files: \");\n" +
            "    print_int(active_count);\n" +
            "    kprint(\"/\");\n" +
            "    print_int(file_count);\n" +
            "    kprint(\"\\n\");\n" +
            "}\n\n" +

            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* MAIN LOOP                                                    */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            
            "/* Start file explorer */\n" +
            "void start_explorer() {\n" +
            "    kprint(\"[OS] Starting File Explorer...\\n\");\n" +
            "    \n" +
            "    /* Scan filesystem */\n" +
            "    scan_disk();\n" +
            "    \n" +
            "    kprint(\"[FS] Found \");\n" +
            "    print_int(file_count);\n" +
            "    kprint(\" files\\n\\n\");\n" +
            "    \n" +
            "    /* Main loop */\n" +
            "    while(1) {\n" +
            "        draw_explorer();\n" +
            "        \n" +
            "        /* Get keyboard input */\n" +
            "        char key = get_char();\n" +
            "        \n" +
            "        /* Navigation */\n" +
            "        if (key == 'w' || key == 'W') {\n" +
            "            selected_idx--;\n" +
            "        }\n" +
            "        else if (key == 's' || key == 'S') {\n" +
            "            selected_idx++;\n" +
            "        }\n" +
            "        /* Actions */\n" +
            "        else if (key == '\\n' || key == '\\r') {\n" +
            "            open_file(selected_idx);\n" +
            "        }\n" +
            "        else if (key == 'd' || key == 'D') {\n" +
            "            delete_file(selected_idx);\n" +
            "        }\n" +
            "        /* Exit */\n" +
            "        else if (key == 0x1B) { /* ESC key */\n" +
            "            kprint(\"[OS] Exiting File Explorer\\n\");\n" +
            "            return;\n" +
            "        }\n" +
            "        \n" +
            "        /* Bounds checking */\n" +
            "        if (selected_idx < 0) selected_idx = 0;\n" +
            "        if (selected_idx >= file_count) selected_idx = file_count - 1;\n" +
            "        \n" +
            "        /* Skip deleted files */\n" +
            "        while(selected_idx < file_count && files[selected_idx].active == 0) {\n" +
            "            selected_idx++;\n" +
            "        }\n" +
            "        if(selected_idx >= file_count) {\n" +
            "            /* Wrap around to first active file */\n" +
            "            selected_idx = 0;\n" +
            "            while(selected_idx < file_count && files[selected_idx].active == 0) {\n" +
            "                selected_idx++;\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "}\n";

        writeFile("fraynix_src/explorer.c", cCode);
    }
    
    private static void writeFile(String path, String content) throws IOException {
        java.io.File file = new java.io.File(path);
        file.getParentFile().mkdirs();
        try (FileWriter fw = new FileWriter(file)) {
            fw.write(content);
        }
    }
}
