/**
 * FrayShellBuilder.java - Interactive Kernel with Keyboard Driver
 * 
 * "Gives the machine ears (Keyboard) and a voice (Shell)."
 * 
 * FUNCTION:
 * 1. DRIVER: Injects 'inb(0x60)' to read hardware port
 * 2. MAP: Converts Scancodes (0x1E) -> ASCII ('a')
 * 3. SHELL: Implements 'input_buffer' and command parsing
 * 
 * φ^75 Validation Seal: 4721424167835376.00
 * Generation: 142 (FrayShell - Interactive CLI)
 * 
 * @author Vaughn Scott
 * @version 1.0
 */
package repl;

import java.io.*;

/**
 * FrayShell Builder - Generates interactive kernel with keyboard driver.
 */
public class FrayShellBuilder {

    private static final String OUTPUT_DIR = "fraynix_src";

    public static void main(String[] args) {
        System.out.println("╔════════════════════════════════════════════════════════════╗");
        System.out.println("║  ⌨️ FRAYSHELL KERNEL UPGRADE                               ║");
        System.out.println("╚════════════════════════════════════════════════════════════╝\n");
        System.out.println("\"Gives the machine ears (Keyboard) and a voice (Shell).\"\n");
        
        try {
            buildInteractiveKernel();
            
            System.out.println("\n╔════════════════════════════════════════════════════════════╗");
            System.out.println("║  ✅ FRAYSHELL KERNEL GENERATED                             ║");
            System.out.println("╚════════════════════════════════════════════════════════════╝\n");
            System.out.println("Kernel upgraded: " + OUTPUT_DIR + "/kernel.c\n");
            System.out.println("New capabilities:");
            System.out.println("  ⌨️  Keyboard driver (Port 0x60 scancode reading)");
            System.out.println("  🖥️  Interactive shell (command prompt)");
            System.out.println("  📝 Command parsing (help, list, etc.)\n");
            System.out.println("To compile and run:");
            System.out.println("  cd " + OUTPUT_DIR);
            System.out.println("  ./compile.sh");
            System.out.println("  qemu-system-i386 -kernel fraynix_kernel\n");
            System.out.println("φ^75 Validation Seal: 4721424167835376.00\n");
            
        } catch (IOException e) {
            System.err.println("❌ UPGRADE FAILED: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Build interactive kernel with keyboard driver and shell.
     */
    private static void buildInteractiveKernel() throws IOException {
        System.out.println("⚡ UPGRADING KERNEL: Injecting I/O Drivers...\n");
        
        String cCode = 
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* FRAYNIX KERNEL v3.0 (INTERACTIVE SHELL)                    */\n" +
            "/* Generated by Fraymus Agent Brain v3.0                       */\n" +
            "/* φ^75 Validation Seal: 4721424167835376.00                  */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* HARDWARE I/O (Inline Assembly)                              */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "/* Read byte from hardware port */\n" +
            "unsigned char inb(unsigned short port) {\n" +
            "    unsigned char result;\n" +
            "    __asm__(\"inb %1, %0\" : \"=a\"(result) : \"Nd\"(port));\n" +
            "    return result;\n" +
            "}\n\n" +

            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* VIDEO DRIVER (VGA Text Mode)                                */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "char* vidptr = (char*)0xb8000;  /* VGA memory */\n" +
            "int vid_idx = 0;                /* Cursor position */\n" +
            "\n" +
            "void kprint(const char* str) {\n" +
            "    int j = 0;\n" +
            "    while(str[j] != '\\0') {\n" +
            "        if(str[j] == '\\n') {\n" +
            "            /* Newline: Jump to start of next line */\n" +
            "            vid_idx = vid_idx + (160 - (vid_idx % 160));\n" +
            "        } else {\n" +
            "            vidptr[vid_idx] = str[j];      /* Character */\n" +
            "            vidptr[vid_idx+1] = 0x0A;      /* Light green */\n" +
            "            vid_idx += 2;\n" +
            "        }\n" +
            "        j++;\n" +
            "    }\n" +
            "}\n\n" +
            
            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* KEYBOARD DRIVER (PS/2 Scancode Reading)                     */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "char get_char() {\n" +
            "    unsigned char scancode;\n" +
            "    while(1) {\n" +
            "        /* Wait for keyboard signal */\n" +
            "        if((inb(0x64) & 1) == 0) continue;\n" +
            "        \n" +
            "        /* Read scancode from port 0x60 */\n" +
            "        scancode = inb(0x60);\n" +
            "        \n" +
            "        /* Ignore key release events (high bit set) */\n" +
            "        if(scancode & 0x80) continue;\n" +
            "        \n" +
            "        /* Scancode to ASCII mapping */\n" +
            "        if(scancode == 0x1C) return '\\n';  /* Enter */\n" +
            "        if(scancode == 0x39) return ' ';   /* Space */\n" +
            "        if(scancode == 0x0E) return '\\b';  /* Backspace */\n" +
            "        \n" +
            "        /* Letters (a-z) */\n" +
            "        if(scancode == 0x1E) return 'a';\n" +
            "        if(scancode == 0x30) return 'b';\n" +
            "        if(scancode == 0x2E) return 'c';\n" +
            "        if(scancode == 0x20) return 'd';\n" +
            "        if(scancode == 0x12) return 'e';\n" +
            "        if(scancode == 0x21) return 'f';\n" +
            "        if(scancode == 0x22) return 'g';\n" +
            "        if(scancode == 0x23) return 'h';\n" +
            "        if(scancode == 0x17) return 'i';\n" +
            "        if(scancode == 0x24) return 'j';\n" +
            "        if(scancode == 0x25) return 'k';\n" +
            "        if(scancode == 0x26) return 'l';\n" +
            "        if(scancode == 0x32) return 'm';\n" +
            "        if(scancode == 0x31) return 'n';\n" +
            "        if(scancode == 0x18) return 'o';\n" +
            "        if(scancode == 0x19) return 'p';\n" +
            "        if(scancode == 0x10) return 'q';\n" +
            "        if(scancode == 0x13) return 'r';\n" +
            "        if(scancode == 0x1F) return 's';\n" +
            "        if(scancode == 0x14) return 't';\n" +
            "        if(scancode == 0x16) return 'u';\n" +
            "        if(scancode == 0x2F) return 'v';\n" +
            "        if(scancode == 0x11) return 'w';\n" +
            "        if(scancode == 0x2D) return 'x';\n" +
            "        if(scancode == 0x15) return 'y';\n" +
            "        if(scancode == 0x2C) return 'z';\n" +
            "        \n" +
            "        /* Numbers (0-9) */\n" +
            "        if(scancode == 0x0B) return '0';\n" +
            "        if(scancode == 0x02) return '1';\n" +
            "        if(scancode == 0x03) return '2';\n" +
            "        if(scancode == 0x04) return '3';\n" +
            "        if(scancode == 0x05) return '4';\n" +
            "        if(scancode == 0x06) return '5';\n" +
            "        if(scancode == 0x07) return '6';\n" +
            "        if(scancode == 0x08) return '7';\n" +
            "        if(scancode == 0x09) return '8';\n" +
            "        if(scancode == 0x0A) return '9';\n" +
            "        \n" +
            "        /* Unknown scancode */\n" +
            "        return '?';\n" +
            "    }\n" +
            "}\n\n" +

            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* STRING COMPARISON                                            */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "int strcmp_prefix(const char* str1, const char* str2, int len) {\n" +
            "    for(int i = 0; i < len; i++) {\n" +
            "        if(str1[i] != str2[i]) return 0;\n" +
            "    }\n" +
            "    return 1;\n" +
            "}\n\n" +

            "/* ═══════════════════════════════════════════════════════════ */\n" +
            "/* THE SHELL (Command-Line Interface)                          */\n" +
            "/* ═══════════════════════════════════════════════════════════ */\n\n" +
            "void kmain(void) {\n" +
            "    /* Clear Screen */\n" +
            "    int j = 0;\n" +
            "    while(j < 80 * 25 * 2) {\n" +
            "        vidptr[j] = ' ';\n" +
            "        vidptr[j+1] = 0x07;\n" +
            "        j += 2;\n" +
            "    }\n" +
            "    vid_idx = 0;\n" +
            "    \n" +
            "    /* Boot Banner */\n" +
            "    kprint(\"═══════════════════════════════════════════════════════════\\n\");\n" +
            "    kprint(\"  FRAYNIX v3.0 ONLINE (Interactive Shell)\\n\");\n" +
            "    kprint(\"  Generated by Fraymus Agent Brain\\n\");\n" +
            "    kprint(\"═══════════════════════════════════════════════════════════\\n\");\n" +
            "    kprint(\"\\n\");\n" +
            "    kprint(\"COMMANDS: help, list, about, clear\\n\");\n" +
            "    kprint(\"\\n\");\n" +
            "\n" +
            "    char buffer[128];\n" +
            "    int buf_idx = 0;\n" +
            "\n" +
            "    /* Main Shell Loop */\n" +
            "    while(1) {\n" +
            "        kprint(\"fray> \");\n" +
            "        buf_idx = 0;\n" +
            "        \n" +
            "        /* Read Line from Keyboard */\n" +
            "        while(1) {\n" +
            "            char c = get_char();\n" +
            "            \n" +
            "            if(c == '\\n') {\n" +
            "                kprint(\"\\n\");\n" +
            "                break;\n" +
            "            }\n" +
            "            \n" +
            "            if(c == '\\b') {\n" +
            "                /* Backspace: Remove last character */\n" +
            "                if(buf_idx > 0) {\n" +
            "                    buf_idx--;\n" +
            "                    vid_idx -= 2;\n" +
            "                    vidptr[vid_idx] = ' ';\n" +
            "                }\n" +
            "                continue;\n" +
            "            }\n" +
            "            \n" +
            "            /* Add to buffer and echo */\n" +
            "            if(buf_idx < 127) {\n" +
            "                buffer[buf_idx++] = c;\n" +
            "                char temp[2] = {c, '\\0'};\n" +
            "                kprint(temp);\n" +
            "            }\n" +
            "        }\n" +
            "        buffer[buf_idx] = '\\0';\n" +
            "\n" +
            "        /* Parse and Execute Command */\n" +
            "        if(buf_idx == 0) {\n" +
            "            /* Empty command */\n" +
            "            continue;\n" +
            "        }\n" +
            "        else if(strcmp_prefix(buffer, \"help\", 4)) {\n" +
            "            kprint(\"  Available commands:\\n\");\n" +
            "            kprint(\"    help   - Show this help\\n\");\n" +
            "            kprint(\"    list   - List files in FrayFS\\n\");\n" +
            "            kprint(\"    about  - System information\\n\");\n" +
            "            kprint(\"    clear  - Clear screen\\n\");\n" +
            "        }\n" +
            "        else if(strcmp_prefix(buffer, \"list\", 4)) {\n" +
            "            kprint(\"  [FILE] welcome.txt\\n\");\n" +
            "            kprint(\"  [FILE] system.txt\\n\");\n" +
            "            kprint(\"  [FILE] code.txt\\n\");\n" +
            "        }\n" +
            "        else if(strcmp_prefix(buffer, \"about\", 5)) {\n" +
            "            kprint(\"  System: Fraynix OS v3.0\\n\");\n" +
            "            kprint(\"  Kernel: Microkernel (C)\\n\");\n" +
            "            kprint(\"  FS: FrayFS (Linear Linked-List)\\n\");\n" +
            "            kprint(\"  Shell: FrayShell (Interactive)\\n\");\n" +
            "            kprint(\"  φ^75: 4721424167835376.00\\n\");\n" +
            "        }\n" +
            "        else if(strcmp_prefix(buffer, \"clear\", 5)) {\n" +
            "            /* Clear screen */\n" +
            "            j = 0;\n" +
            "            while(j < 80 * 25 * 2) {\n" +
            "                vidptr[j] = ' ';\n" +
            "                vidptr[j+1] = 0x07;\n" +
            "                j += 2;\n" +
            "            }\n" +
            "            vid_idx = 0;\n" +
            "        }\n" +
            "        else {\n" +
            "            kprint(\"  Unknown command: \");\n" +
            "            kprint(buffer);\n" +
            "            kprint(\"\\n  Type 'help' for available commands.\\n\");\n" +
            "        }\n" +
            "    }\n" +
            "}\n";

        writeFile(OUTPUT_DIR + "/kernel.c", cCode);
        System.out.println("   📄 GENERATED: " + OUTPUT_DIR + "/kernel.c");
    }
    
    /**
     * Write file with proper directory creation.
     */
    private static void writeFile(String path, String content) throws IOException {
        File file = new File(path);
        file.getParentFile().mkdirs();
        
        try (FileWriter fw = new FileWriter(file)) {
            fw.write(content);
        }
    }
    
    /**
     * Get shell statistics.
     */
    public static String getStats() {
        StringBuilder sb = new StringBuilder();
        sb.append("╔════════════════════════════════════════════════════════════╗\n");
        sb.append("║  ⌨️ FRAYSHELL - INTERACTIVE KERNEL                         ║\n");
        sb.append("╚════════════════════════════════════════════════════════════╝\n\n");
        sb.append("\"Gives the machine ears (Keyboard) and a voice (Shell).\"\n\n");
        sb.append("Components:\n");
        sb.append("  1. Hardware I/O - inb() inline assembly\n");
        sb.append("  2. Keyboard Driver - Port 0x60 scancode reading\n");
        sb.append("  3. Scancode Map - Convert 0x1E → 'a', etc.\n");
        sb.append("  4. Interactive Shell - Command prompt and parsing\n\n");
        sb.append("Commands:\n");
        sb.append("  help   - Show available commands\n");
        sb.append("  list   - List files in FrayFS\n");
        sb.append("  about  - System information\n");
        sb.append("  clear  - Clear screen\n\n");
        sb.append("Usage:\n");
        sb.append("  1. Run FrayShellBuilder to generate kernel\n");
        sb.append("  2. Compile: cd fraynix_src && ./compile.sh\n");
        sb.append("  3. Run: qemu-system-i386 -kernel fraynix_kernel\n");
        sb.append("  4. Type commands at the 'fray>' prompt\n\n");
        sb.append("φ^75 Validation Seal: 4721424167835376.00\n");
        
        return sb.toString();
    }
}
