package fraymus;

import fraymus.alchemy.PhilosophersStone;
import java.util.Scanner;

/**
 * 💎 ALCHEMY DEMO - Interactive Philosopher's Stone
 * 
 * THE GOD PROTOCOL: Layer 5 - Runtime Self-Modification
 * 
 * Type English commands, watch them become executable Java.
 * The system rewrites itself in real-time.
 */
public class AlchemyDemo {
    
    public static void main(String[] args) {
        System.out.println("╔═══════════════════════════════════════════════════════════════╗");
        System.out.println("║                                                               ║");
        System.out.println("║          💎 THE PHILOSOPHER'S STONE                           ║");
        System.out.println("║          Universal Transmuter - Runtime Compiler             ║");
        System.out.println("║                                                               ║");
        System.out.println("║  \"Lead → Gold. Intent → Execution.\"                          ║");
        System.out.println("║                                                               ║");
        System.out.println("╚═══════════════════════════════════════════════════════════════╝");
        System.out.println();
        System.out.println("PROTOCOL:");
        System.out.println("  1. You type English intent");
        System.out.println("  2. LLM generates Java code");
        System.out.println("  3. Java compiler compiles it");
        System.out.println("  4. If errors → Feed back to LLM → Retry");
        System.out.println("  5. Execute the generated bytecode");
        System.out.println();
        System.out.println("This is AUTOPOIESIS. The system creates itself.");
        System.out.println();
        System.out.println("═══════════════════════════════════════════════════════════════");
        System.out.println();
        
        PhilosophersStone stone = new PhilosophersStone();
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("EXAMPLE COMMANDS:");
        System.out.println("  - Calculate the 100th Fibonacci number using BigInteger");
        System.out.println("  - Generate the first 20 prime numbers");
        System.out.println("  - Calculate factorial of 50");
        System.out.println("  - Create a palindrome checker for 'racecar'");
        System.out.println("  - Build a simple calculator that adds 123 and 456");
        System.out.println();
        System.out.println("Type 'quit' to exit, 'status' for statistics");
        System.out.println("═══════════════════════════════════════════════════════════════");
        System.out.println();
        
        while (true) {
            System.out.print("TRANSMUTE> ");
            String input = scanner.nextLine().trim();
            
            if (input.isEmpty()) {
                continue;
            }
            
            if (input.equalsIgnoreCase("quit") || input.equalsIgnoreCase("exit")) {
                System.out.println();
                System.out.println("═══════════════════════════════════════════════════════════════");
                System.out.println(stone.status());
                System.out.println("═══════════════════════════════════════════════════════════════");
                System.out.println();
                System.out.println("💎 The Stone returns to dormancy.");
                System.out.println("   \"All that is gold does not glitter.\"");
                System.out.println();
                break;
            }
            
            if (input.equalsIgnoreCase("status") || input.equalsIgnoreCase("stats")) {
                System.out.println();
                System.out.println(stone.status());
                System.out.println();
                continue;
            }
            
            if (input.equalsIgnoreCase("help")) {
                System.out.println();
                System.out.println("HELP:");
                System.out.println("  - Type any English description of what you want the code to do");
                System.out.println("  - The Stone will generate, compile, and execute Java code");
                System.out.println("  - If compilation fails, it will self-heal by asking the LLM to fix errors");
                System.out.println("  - Type 'status' to see statistics");
                System.out.println("  - Type 'quit' to exit");
                System.out.println();
                continue;
            }
            
            System.out.println();
            
            try {
                stone.transmutate(input);
            } catch (Exception e) {
                System.out.println("❌ TRANSMUTATION ERROR: " + e.getMessage());
                e.printStackTrace();
            }
            
            System.out.println();
        }
        
        scanner.close();
    }
}
