package fraymus.living;

import java.util.*;

/**
 * LIVING CODE GENERATOR - Evolution Engine
 * 
 * Population manager and code generator.
 * Evolves circuits and generates living code.
 */
public class LivingCodeGenerator {
    
    private List<LivingCircuit> population;
    private int generation;
    private static final int MAX_POPULATION = 20;
    private static final int GENESIS_POPULATION = 5;
    
    public LivingCodeGenerator() {
        this.population = new ArrayList<>();
        this.generation = 0;
        
        // Genesis: Create initial population
        for (int i = 0; i < GENESIS_POPULATION; i++) {
            population.add(new LivingCircuit());
        }
    }
    
    /**
     * Evolve population for N cycles
     */
    public void evolve(int cycles) {
        for (int i = 0; i < cycles; i++) {
            List<LivingCircuit> nextGen = new ArrayList<>(population);
            
            // Update all circuits
            for (LivingCircuit circuit : population) {
                circuit.update();
                
                // Reproduction
                if (circuit.readyToReproduce() && nextGen.size() < MAX_POPULATION) {
                    nextGen.add(circuit.reproduce());
                }
            }
            
            // Natural selection (keep fittest)
            if (nextGen.size() > MAX_POPULATION) {
                nextGen.sort((a, b) -> Double.compare(b.getFitness(), a.getFitness()));
                nextGen = new ArrayList<>(nextGen.subList(0, MAX_POPULATION));
            }
            
            population = nextGen;
            generation++;
        }
    }
    
    /**
     * Generate code from intent
     */
    public String generateCode(String intent) {
        // Evolve population to find best circuits
        evolve(50);
        
        // Get top 3 circuits
        List<LivingCircuit> best = getBestCircuits(3);
        
        // Generate code based on intent
        String format = detectFormat(intent);
        
        switch (format) {
            case "java":
                return generateJavaCode(intent, best);
            case "python":
                return generatePythonCode(intent, best);
            case "arduino":
                return generateArduinoCode(intent, best);
            default:
                return generatePythonCode(intent, best);
        }
    }
    
    /**
     * Detect target format from intent
     */
    private String detectFormat(String intent) {
        String lower = intent.toLowerCase();
        
        if (lower.contains("java")) return "java";
        if (lower.contains("arduino") || lower.contains("ino")) return "arduino";
        if (lower.contains("python") || lower.contains("py")) return "python";
        
        return "python"; // default
    }
    
    /**
     * Generate Java code
     */
    private String generateJavaCode(String intent, List<LivingCircuit> circuits) {
        StringBuilder code = new StringBuilder();
        
        code.append("// LIVING CODE - Generated by Fraymus\n");
        code.append("// Intent: ").append(intent).append("\n");
        code.append("// Generation: ").append(generation).append("\n\n");
        
        code.append("public class LivingCode {\n\n");
        
        // Embed circuits
        code.append("    // Evolved Logic Circuits\n");
        for (int i = 0; i < circuits.size(); i++) {
            LivingCircuit circuit = circuits.get(i);
            code.append("    // Circuit ").append(i).append(": ");
            code.append(circuit.toString()).append("\n");
            
            LogicGate[] gates = circuit.getBrain().getGates();
            code.append("    // Gates: ");
            for (LogicGate gate : gates) {
                code.append(gate.getTypeName()).append(" ");
            }
            code.append("\n");
        }
        
        code.append("\n");
        code.append("    public static void main(String[] args) {\n");
        code.append("        // TODO: Implement ").append(intent).append("\n");
        code.append("        System.out.println(\"Living code generated!\");\n");
        code.append("    }\n");
        code.append("}\n");
        
        return code.toString();
    }
    
    /**
     * Generate Python code
     */
    private String generatePythonCode(String intent, List<LivingCircuit> circuits) {
        StringBuilder code = new StringBuilder();
        
        code.append("# LIVING CODE - Generated by Fraymus\n");
        code.append("# Intent: ").append(intent).append("\n");
        code.append("# Generation: ").append(generation).append("\n\n");
        
        code.append("# Evolved Logic Circuits\n");
        for (int i = 0; i < circuits.size(); i++) {
            LivingCircuit circuit = circuits.get(i);
            code.append("# Circuit ").append(i).append(": ");
            code.append(circuit.toString()).append("\n");
        }
        
        code.append("\n");
        code.append("def main():\n");
        code.append("    # TODO: Implement ").append(intent).append("\n");
        code.append("    print('Living code generated!')\n\n");
        code.append("if __name__ == '__main__':\n");
        code.append("    main()\n");
        
        return code.toString();
    }
    
    /**
     * Generate Arduino code
     */
    private String generateArduinoCode(String intent, List<LivingCircuit> circuits) {
        StringBuilder code = new StringBuilder();
        
        code.append("// LIVING CODE - Generated by Fraymus\n");
        code.append("// Intent: ").append(intent).append("\n");
        code.append("// Generation: ").append(generation).append("\n\n");
        
        code.append("// Evolved Logic Circuits\n");
        for (int i = 0; i < circuits.size(); i++) {
            LivingCircuit circuit = circuits.get(i);
            code.append("// Circuit ").append(i).append(": ");
            code.append(circuit.toString()).append("\n");
        }
        
        code.append("\n");
        code.append("void setup() {\n");
        code.append("    Serial.begin(9600);\n");
        code.append("    // TODO: Implement ").append(intent).append("\n");
        code.append("}\n\n");
        code.append("void loop() {\n");
        code.append("    // Living code running\n");
        code.append("    delay(1000);\n");
        code.append("}\n");
        
        return code.toString();
    }
    
    /**
     * Get best circuits by fitness
     */
    public List<LivingCircuit> getBestCircuits(int count) {
        List<LivingCircuit> sorted = new ArrayList<>(population);
        sorted.sort((a, b) -> Double.compare(b.getFitness(), a.getFitness()));
        return sorted.subList(0, Math.min(count, sorted.size()));
    }
    
    /**
     * Show population statistics
     */
    public void showStats() {
        System.out.println();
        System.out.println("🧬 LIVING CODE GENERATOR STATISTICS");
        System.out.println("========================================");
        System.out.println();
        System.out.println("   Generation: " + generation);
        System.out.println("   Population: " + population.size());
        System.out.println();
        
        double avgFitness = population.stream()
            .mapToDouble(LivingCircuit::getFitness)
            .average()
            .orElse(0);
        
        double avgFreq = population.stream()
            .mapToDouble(c -> c.getDNA().getFrequency())
            .average()
            .orElse(0);
        
        System.out.println("   Average Fitness: " + String.format("%.2f", avgFitness));
        System.out.println("   Average Frequency: " + String.format("%.2f Hz", avgFreq));
        System.out.println();
        
        System.out.println("   Top 3 Circuits:");
        List<LivingCircuit> best = getBestCircuits(3);
        for (int i = 0; i < best.size(); i++) {
            System.out.println("   " + (i + 1) + ". " + best.get(i));
        }
        System.out.println();
    }
    
    public int getGeneration() {
        return generation;
    }
    
    public int getPopulation() {
        return population.size();
    }
}
