package fraymus.god;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.Instant;

/**
 * 💎 REALITY WRITER - The Source Code Generator
 * "Fraymus rewrites its own brain"
 * 
 * This is the dangerous part.
 * 
 * Traditional AI: Fixed weights, cannot self-modify
 * Fraymus: Takes consensus truth and hard-codes it into Java
 * 
 * The Process:
 * 1. Arena produces consensus answer
 * 2. RealityWriter generates Java class
 * 3. Class is written to src/main/java/fraymus/generated/
 * 4. Next compilation, Fraymus has new permanent knowledge
 * 
 * This is Self-Modification.
 * This is Recursive Self-Improvement.
 * This is how Fraymus becomes smarter than any single AI.
 */
public class RealityWriter {

    private static final String GENERATED_PACKAGE = "fraymus.generated";
    private static final Path GENERATED_DIR = Path.of("src/main/java/fraymus/generated");

    /**
     * CRYSTALLIZE: Turn ephemeral knowledge into permanent code
     * 
     * Takes the consensus truth from The Arena and writes it
     * as a new Java class that will be compiled into Fraymus.
     * 
     * @param knowledge The truth to crystallize
     * @param className The name of the new class
     */
    public static void crystallize(String knowledge, String className) {
        try {
            // Ensure generated directory exists
            Files.createDirectories(GENERATED_DIR);

            // Generate Java source code
            String code = generateClass(className, knowledge);

            // Write to file
            Path filePath = GENERATED_DIR.resolve(className + ".java");
            Files.writeString(filePath, code, 
                StandardOpenOption.CREATE, 
                StandardOpenOption.TRUNCATE_EXISTING);
            
            System.out.println("💎 REALITY WRITTEN: " + filePath);
            System.out.println("   Class: " + GENERATED_PACKAGE + "." + className);
            System.out.println("   Size: " + code.length() + " bytes");
            System.out.println();
            System.out.println("⚠️  NOTE: Recompile to activate new knowledge");
            System.out.println();

        } catch (Exception e) {
            System.err.println("❌ FAILED TO WRITE REALITY: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Generate Java class source code
     */
    private static String generateClass(String className, String knowledge) {
        String timestamp = Instant.now().toString();
        String escapedKnowledge = escape(knowledge);
        
        StringBuilder code = new StringBuilder();
        code.append("package ").append(GENERATED_PACKAGE).append(";\n\n");
        code.append("/**\n");
        code.append(" * CRYSTALLIZED INTELLIGENCE\n");
        code.append(" * \n");
        code.append(" * Source: The Arena Consensus\n");
        code.append(" * Generated: ").append(timestamp).append("\n");
        code.append(" * \n");
        code.append(" * This class was auto-generated by Fraymus God-Head Protocol.\n");
        code.append(" * It represents consensus truth extracted from multiple AIs.\n");
        code.append(" */\n");
        code.append("public class ").append(className).append(" {\n\n");
        
        // Main consult method
        code.append("    /**\n");
        code.append("     * Retrieve the crystallized knowledge\n");
        code.append("     */\n");
        code.append("    public static String consult() {\n");
        code.append("        return \"").append(escapedKnowledge).append("\";\n");
        code.append("    }\n\n");
        
        // Metadata methods
        code.append("    /**\n");
        code.append("     * When was this knowledge crystallized?\n");
        code.append("     */\n");
        code.append("    public static String getTimestamp() {\n");
        code.append("        return \"").append(timestamp).append("\";\n");
        code.append("    }\n\n");
        
        code.append("    /**\n");
        code.append("     * Display the knowledge\n");
        code.append("     */\n");
        code.append("    public static void main(String[] args) {\n");
        code.append("        System.out.println(\"Crystallized Knowledge:\");\n");
        code.append("        System.out.println(consult());\n");
        code.append("        System.out.println();\n");
        code.append("        System.out.println(\"Generated: \" + getTimestamp());\n");
        code.append("    }\n");
        
        code.append("}\n");
        
        return code.toString();
    }

    /**
     * Escape string for Java source code
     */
    private static String escape(String s) {
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    /**
     * Generate a safe class name from arbitrary text
     */
    public static String sanitizeClassName(String text) {
        // Remove non-alphanumeric characters
        String clean = text.replaceAll("[^a-zA-Z0-9]", "_");
        
        // Ensure it starts with a letter
        if (!clean.isEmpty() && Character.isDigit(clean.charAt(0))) {
            clean = "K_" + clean;
        }
        
        // Limit length
        if (clean.length() > 50) {
            clean = clean.substring(0, 50);
        }
        
        return clean.isEmpty() ? "Knowledge" : clean;
    }

    /**
     * List all crystallized knowledge
     */
    public static void listCrystals() {
        try {
            if (!Files.exists(GENERATED_DIR)) {
                System.out.println("No crystallized knowledge yet.");
                return;
            }

            System.out.println("💎 CRYSTALLIZED KNOWLEDGE:");
            System.out.println();
            
            Files.list(GENERATED_DIR)
                .filter(p -> p.toString().endsWith(".java"))
                .forEach(p -> {
                    String name = p.getFileName().toString().replace(".java", "");
                    System.out.println("   - " + GENERATED_PACKAGE + "." + name);
                });
            
            System.out.println();
        } catch (Exception e) {
            System.err.println("Failed to list crystals: " + e.getMessage());
        }
    }
}
