package love;

/**
 * Module: loveMain for love
 * Generated by Genesis Architect V1
 */
public class loveMain {

    public loveMain() {
        // Initialize
    }

    public static void main(String[] args) {
        System.out.println("loveMain started");
    }
}
