/**
 * API Server
 * Generated by Fraynix Genesis Engine
 * Technology: Express
 * Description: REST API endpoints
 */

const express = require('express');
const app = express();

// REST API endpoints
app.use(express.json());

app.get('/', (req, res) => {
  res.json({ status: 'online', module: 'API Server' });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`API Server running on port ${PORT}`);
});

module.exports = app;
