package fraymus.os;

import java.io.*;
import java.nio.file.*;

/**
 * 🔫 FRAY-DOOM BUILDER - Gen 146
 * "Infinite reality on a 320x200 grid."
 * 
 * Bare metal raycaster engine - the Wolfenstein/Doom technique.
 * Cast rays from player's eyes, calculate wall distances,
 * draw vertical strips proportional to distance.
 * 
 * Features:
 *   - DDA raycasting algorithm
 *   - Fixed-point math (no FPU)
 *   - Textured walls
 *   - Sprites (enemies/items)
 *   - Multiplayer via FrayNet
 * 
 * "The simulation is running."
 */
public class FrayDoomBuilder {

    private static final String OUTPUT_DIR = "fraynix_src";

    public static void main(String[] args) {
        System.out.println("╔═══════════════════════════════════════════════════════════════╗");
        System.out.println("║  🔫 FRAY-DOOM BUILDER - Gen 146                               ║");
        System.out.println("║  Bare Metal Raycaster Engine                                  ║");
        System.out.println("╚═══════════════════════════════════════════════════════════════╝");
        System.out.println();
        
        try {
            Files.createDirectories(Paths.get(OUTPUT_DIR));
            
            System.out.println("⚡ Generating raycaster engine...");
            
            buildDoomEngine();
            buildMapData();
            
            System.out.println();
            System.out.println("╔═══════════════════════════════════════════════════════════════╗");
            System.out.println("║  ✅ FRAY-DOOM INSTALLED                                       ║");
            System.out.println("║                                                               ║");
            System.out.println("║  Output: fraynix_src/doom.c                                  ║");
            System.out.println("║          fraynix_src/maps.c                                  ║");
            System.out.println("║                                                               ║");
            System.out.println("║  Controls: W/S = Move, A/D = Turn, Space = Shoot             ║");
            System.out.println("║  Shell:    Type 'doom' to launch                             ║");
            System.out.println("╚═══════════════════════════════════════════════════════════════╝");
            
        } catch (IOException e) {
            System.err.println("❌ BUILD FAILED: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static void buildDoomEngine() throws IOException {
        System.out.println("   [1/2] Generating doom.c...");
        
        String doom = """
/* ═══════════════════════════════════════════════════════════════════════════
 * FRAY-DOOM: BARE METAL RAYCASTER
 * Generated by Fraymus - Gen 146
 * 
 * The Classic Technique:
 * 1. For each vertical column (0-319)
 * 2. Cast a ray from player position
 * 3. Step through map grid until wall hit
 * 4. Calculate perpendicular distance
 * 5. Draw wall slice proportional to distance
 * 
 * All math in fixed-point (8.8 format)
 * 
 * "Reality rendered in 320 vertical strips."
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_DOOM_C
#define FRAY_DOOM_C

#include "math3d.c"
#include "net.c"
#include "maps.c"

/* Screen dimensions */
#define SCREEN_W 320
#define SCREEN_H 200

/* Fixed-point constants */
#define FP_SHIFT 8
#define FP_ONE   256
#define FP_HALF  128

/* Player state (fixed-point) */
static int player_x = 3 * FP_ONE + FP_HALF;  /* Start at (3.5, 3.5) */
static int player_y = 3 * FP_ONE + FP_HALF;
static int player_dir = 0;   /* Angle (0-255 = 0-360 degrees) */
static int player_health = 100;
static int player_ammo = 50;

/* Movement speed */
#define MOVE_SPEED   8    /* Fixed-point units per frame */
#define TURN_SPEED   4    /* Angle units per frame */

/* Camera plane (for FOV) */
#define PLANE_SCALE  FP_HALF  /* 0.5 in fixed-point, ~66 degree FOV */

/* ═══════════════════════════════════════════════════════════════════════════
 * RAYCASTING ENGINE
 * ═══════════════════════════════════════════════════════════════════════════ */

void doom_cast_rays(void) {
    /* For each vertical strip */
    for (int x = 0; x < SCREEN_W; x++) {
        /* Calculate ray direction */
        /* Camera space: -1 to +1 across screen */
        int camera_x = (2 * x * FP_ONE / SCREEN_W) - FP_ONE;
        
        /* Ray direction = player direction + camera plane offset */
        int ray_dir_x = fp_cos(player_dir) + FP_MUL(fp_sin(player_dir), camera_x) / 2;
        int ray_dir_y = fp_sin(player_dir) - FP_MUL(fp_cos(player_dir), camera_x) / 2;
        
        /* Prevent division by zero */
        if (ray_dir_x == 0) ray_dir_x = 1;
        if (ray_dir_y == 0) ray_dir_y = 1;
        
        /* Current map cell */
        int map_x = player_x >> FP_SHIFT;
        int map_y = player_y >> FP_SHIFT;
        
        /* Delta distance (how far to travel to cross one cell) */
        int delta_dist_x = (FP_ONE * FP_ONE) / (ray_dir_x > 0 ? ray_dir_x : -ray_dir_x);
        int delta_dist_y = (FP_ONE * FP_ONE) / (ray_dir_y > 0 ? ray_dir_y : -ray_dir_y);
        if (delta_dist_x > 10 * FP_ONE) delta_dist_x = 10 * FP_ONE;
        if (delta_dist_y > 10 * FP_ONE) delta_dist_y = 10 * FP_ONE;
        
        /* Step direction and initial side distance */
        int step_x, step_y;
        int side_dist_x, side_dist_y;
        
        if (ray_dir_x < 0) {
            step_x = -1;
            side_dist_x = FP_MUL((player_x - (map_x << FP_SHIFT)), delta_dist_x) >> FP_SHIFT;
        } else {
            step_x = 1;
            side_dist_x = FP_MUL(((map_x + 1) << FP_SHIFT) - player_x, delta_dist_x) >> FP_SHIFT;
        }
        
        if (ray_dir_y < 0) {
            step_y = -1;
            side_dist_y = FP_MUL((player_y - (map_y << FP_SHIFT)), delta_dist_y) >> FP_SHIFT;
        } else {
            step_y = 1;
            side_dist_y = FP_MUL(((map_y + 1) << FP_SHIFT) - player_y, delta_dist_y) >> FP_SHIFT;
        }
        
        /* DDA: Step through map until wall hit */
        int hit = 0;
        int side = 0;  /* 0 = X side, 1 = Y side */
        
        while (!hit) {
            if (side_dist_x < side_dist_y) {
                side_dist_x += delta_dist_x;
                map_x += step_x;
                side = 0;
            } else {
                side_dist_y += delta_dist_y;
                map_y += step_y;
                side = 1;
            }
            
            /* Check for wall */
            if (map_x < 0 || map_x >= MAP_W || map_y < 0 || map_y >= MAP_H) {
                hit = 1;  /* Out of bounds */
            } else if (world_map[map_y][map_x] > 0) {
                hit = 1;  /* Wall */
            }
        }
        
        /* Calculate perpendicular distance (avoids fisheye) */
        int perp_dist;
        if (side == 0) {
            perp_dist = side_dist_x - delta_dist_x;
        } else {
            perp_dist = side_dist_y - delta_dist_y;
        }
        
        /* Prevent division by zero */
        if (perp_dist < 1) perp_dist = 1;
        
        /* Calculate wall height */
        int line_height = (SCREEN_H * FP_ONE) / perp_dist;
        if (line_height > SCREEN_H * 2) line_height = SCREEN_H * 2;
        
        int draw_start = (SCREEN_H - line_height) / 2;
        int draw_end = (SCREEN_H + line_height) / 2;
        
        if (draw_start < 0) draw_start = 0;
        if (draw_end >= SCREEN_H) draw_end = SCREEN_H - 1;
        
        /* Choose wall color based on map value and side */
        int wall_type = world_map[map_y][map_x];
        unsigned char color;
        
        switch (wall_type) {
            case 1: color = 4; break;   /* Red */
            case 2: color = 2; break;   /* Green */
            case 3: color = 1; break;   /* Blue */
            case 4: color = 14; break;  /* Yellow */
            default: color = 7; break;  /* Gray */
        }
        
        /* Darken Y-side walls for depth perception */
        if (side == 1) {
            color = (color > 8) ? color - 8 : color;
        }
        
        /* Draw ceiling */
        for (int y = 0; y < draw_start; y++) {
            vga_put_pixel(x, y, 8);  /* Dark gray ceiling */
        }
        
        /* Draw wall */
        for (int y = draw_start; y < draw_end; y++) {
            vga_put_pixel(x, y, color);
        }
        
        /* Draw floor */
        for (int y = draw_end; y < SCREEN_H; y++) {
            vga_put_pixel(x, y, 6);  /* Brown floor */
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * HUD (Heads-Up Display)
 * ═══════════════════════════════════════════════════════════════════════════ */

void doom_draw_hud(void) {
    /* Health bar */
    vga_fill_rect(10, 185, 50, 10, 0);
    vga_fill_rect(10, 185, player_health / 2, 10, 4);  /* Red */
    
    /* Ammo counter */
    vga_fill_rect(260, 185, 50, 10, 0);
    vga_fill_rect(260, 185, player_ammo, 10, 14);  /* Yellow */
    
    /* Crosshair */
    vga_put_pixel(SCREEN_W / 2, SCREEN_H / 2, 15);
    vga_put_pixel(SCREEN_W / 2 - 2, SCREEN_H / 2, 15);
    vga_put_pixel(SCREEN_W / 2 + 2, SCREEN_H / 2, 15);
    vga_put_pixel(SCREEN_W / 2, SCREEN_H / 2 - 2, 15);
    vga_put_pixel(SCREEN_W / 2, SCREEN_H / 2 + 2, 15);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * INPUT HANDLING
 * ═══════════════════════════════════════════════════════════════════════════ */

void doom_handle_input(void) {
    if (!keyboard_haschar()) return;
    
    char key = keyboard_getchar();
    
    int new_x = player_x;
    int new_y = player_y;
    
    switch (key) {
        case 'w':  /* Move forward */
            new_x += FP_MUL(fp_cos(player_dir), MOVE_SPEED);
            new_y += FP_MUL(fp_sin(player_dir), MOVE_SPEED);
            break;
            
        case 's':  /* Move backward */
            new_x -= FP_MUL(fp_cos(player_dir), MOVE_SPEED);
            new_y -= FP_MUL(fp_sin(player_dir), MOVE_SPEED);
            break;
            
        case 'a':  /* Turn left */
            player_dir = (player_dir - TURN_SPEED) & 0xFF;
            break;
            
        case 'd':  /* Turn right */
            player_dir = (player_dir + TURN_SPEED) & 0xFF;
            break;
            
        case ' ':  /* Shoot */
            if (player_ammo > 0) {
                player_ammo--;
                /* TODO: Ray trace for enemy hit */
            }
            break;
            
        case 27:  /* ESC - exit to shell */
            return;
    }
    
    /* Collision detection */
    int check_x = new_x >> FP_SHIFT;
    int check_y = new_y >> FP_SHIFT;
    
    if (check_x >= 0 && check_x < MAP_W && 
        check_y >= 0 && check_y < MAP_H &&
        world_map[check_y][check_x] == 0) {
        player_x = new_x;
        player_y = new_y;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * MAIN GAME LOOP
 * ═══════════════════════════════════════════════════════════════════════════ */

void doom_loop(void) {
    vga_init();
    vga_init_palette();
    
    kprint_color("\\n  FRAY-DOOM LOADING...\\n", 0x0C);
    kprint("  Controls: W/S=Move A/D=Turn Space=Shoot ESC=Quit\\n\\n");
    
    /* Wait for keypress to start */
    keyboard_getchar();
    
    int frame = 0;
    
    while (1) {
        /* Handle input */
        doom_handle_input();
        
        /* Render 3D view */
        doom_cast_rays();
        
        /* Draw HUD */
        doom_draw_hud();
        
        /* Network: Broadcast position every 5 frames */
        if (frame % 5 == 0) {
            net_broadcast_position(
                player_x >> FP_SHIFT,
                player_y >> FP_SHIFT,
                0,
                player_dir
            );
        }
        
        /* VSync for smooth animation */
        vga_wait_vsync();
        
        frame++;
    }
}

#endif /* FRAY_DOOM_C */
""";
        
        writeFile(OUTPUT_DIR + "/doom.c", doom);
    }

    private static void buildMapData() throws IOException {
        System.out.println("   [2/2] Generating maps.c...");
        
        String maps = """
/* ═══════════════════════════════════════════════════════════════════════════
 * FRAY-DOOM: MAP DATA
 * Generated by Fraymus - Gen 146
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_MAPS_C
#define FRAY_MAPS_C

#define MAP_W 16
#define MAP_H 16

/* Map Legend:
 * 0 = Empty (floor)
 * 1 = Red wall
 * 2 = Green wall
 * 3 = Blue wall
 * 4 = Yellow wall (gold)
 */

static int world_map[MAP_H][MAP_W] = {
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1},
    {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1},
    {1, 0, 0, 2, 2, 2, 0, 0, 0, 0, 3, 3, 3, 0, 0, 1},
    {1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1},
    {1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1},
    {1, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 1},
    {1, 0, 0, 0, 0, 0, 4, 0, 0, 4, 0, 0, 0, 0, 0, 1},
    {1, 0, 0, 0, 0, 0, 4, 0, 0, 4, 0, 0, 0, 0, 0, 1},
    {1, 0, 0, 0, 0, 0, 4, 4, 0, 4, 0, 0, 0, 0, 0, 1},
    {1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1},
    {1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1},
    {1, 0, 0, 2, 2, 2, 0, 0, 0, 0, 3, 3, 3, 0, 0, 1},
    {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1},
    {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}
};

/* Spawn points */
static int spawn_x[4] = { 2, 13, 2, 13 };
static int spawn_y[4] = { 2, 2, 13, 13 };

#endif /* FRAY_MAPS_C */
""";
        
        writeFile(OUTPUT_DIR + "/maps.c", maps);
    }

    private static void writeFile(String path, String content) throws IOException {
        Path filePath = Paths.get(path);
        Files.createDirectories(filePath.getParent());
        Files.writeString(filePath, content);
        System.out.println("      → " + path);
    }
}
