package fraymus.os;

import java.io.*;
import java.nio.file.*;

/**
 * 🧱 FRAY COMPILER BUILDER - Gen 143
 * "The tool that lets the machine reprogram itself."
 * 
 * Generates a C file implementing:
 * 1. LEXER: Breaks "10 5 + ." into tokens
 * 2. COMPILER: Converts tokens to stack operations
 * 3. VM: Stack-based virtual CPU executing bytecode
 * 
 * Language: Fray-Forth (Stack-based, Reverse Polish Notation)
 * 
 * Operations:
 *   Numbers   → Push to stack
 *   +         → Add top two values
 *   -         → Subtract
 *   *         → Multiply
 *   /         → Divide
 *   .         → Print and pop top of stack
 *   dup       → Duplicate top of stack
 *   swap      → Swap top two values
 *   drop      → Discard top of stack
 *   
 * Example: "10 5 + ." → Push 10, Push 5, Add, Print → Output: 15
 * 
 * "The child learns to calculate."
 */
public class FrayCompilerBuilder {

    private static final String OUTPUT_DIR = "fraynix_src";

    public static void main(String[] args) {
        System.out.println("╔═══════════════════════════════════════════════════════════════╗");
        System.out.println("║  🧱 FRAY COMPILER BUILDER - Gen 143                           ║");
        System.out.println("║  Stack-Based Virtual Machine                                  ║");
        System.out.println("╚═══════════════════════════════════════════════════════════════╝");
        System.out.println();
        
        try {
            Files.createDirectories(Paths.get(OUTPUT_DIR));
            
            System.out.println("⚡ Generating compiler components...");
            
            buildCompiler();
            updateKernelWithCompiler();
            
            System.out.println();
            System.out.println("╔═══════════════════════════════════════════════════════════════╗");
            System.out.println("║  ✅ FRAY-C COMPILER INSTALLED                                 ║");
            System.out.println("║                                                               ║");
            System.out.println("║  Output: fraynix_src/compiler.c                              ║");
            System.out.println("║                                                               ║");
            System.out.println("║  Usage in FrayShell:                                         ║");
            System.out.println("║    fray> run 10 5 + .       → Output: 15                     ║");
            System.out.println("║    fray> run 100 50 - .     → Output: 50                     ║");
            System.out.println("║    fray> run 7 8 * .        → Output: 56                     ║");
            System.out.println("║    fray> run 3 dup * .      → Output: 9                      ║");
            System.out.println("╚═══════════════════════════════════════════════════════════════╝");
            
        } catch (IOException e) {
            System.err.println("❌ BUILD FAILED: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static void buildCompiler() throws IOException {
        System.out.println("   [1/2] Generating compiler.c...");
        
        String compiler = """
/* ═══════════════════════════════════════════════════════════════════════════
 * FRAY-C COMPILER & VIRTUAL MACHINE
 * Generated by Fraymus - Gen 143
 * 
 * A stack-based interpreter running inside the Fraynix kernel.
 * Language: Fray-Forth (Reverse Polish Notation)
 * 
 * Examples:
 *   "10 5 + ."     → 15
 *   "3 dup * ."    → 9
 *   "100 50 - ."   → 50
 *   "7 8 * 2 / ."  → 28
 * 
 * "The machine calculates. The machine evolves."
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef FRAY_COMPILER_C
#define FRAY_COMPILER_C

/* ═══════════════════════════════════════════════════════════════════════════
 * VIRTUAL MACHINE STATE
 * ═══════════════════════════════════════════════════════════════════════════ */

#define STACK_SIZE 256
#define MAX_VARS 26

static int vm_stack[STACK_SIZE];
static int vm_sp = 0;  /* Stack pointer */
static int vm_vars[MAX_VARS];  /* Variables a-z */
static int vm_running = 1;

/* Stack operations */
static inline void vm_push(int val) {
    if (vm_sp < STACK_SIZE) {
        vm_stack[vm_sp++] = val;
    } else {
        kprint_color("  Stack overflow!\\n", 0x0C);
    }
}

static inline int vm_pop(void) {
    if (vm_sp > 0) {
        return vm_stack[--vm_sp];
    } else {
        kprint_color("  Stack underflow!\\n", 0x0C);
        return 0;
    }
}

static inline int vm_peek(void) {
    if (vm_sp > 0) {
        return vm_stack[vm_sp - 1];
    }
    return 0;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * TOKEN PARSER
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Skip whitespace */
static char* skip_ws(char* p) {
    while (*p == ' ' || *p == '\\t') p++;
    return p;
}

/* Parse integer */
static int parse_int(char** pp) {
    char* p = *pp;
    int neg = 0;
    int num = 0;
    
    if (*p == '-' && p[1] >= '0' && p[1] <= '9') {
        neg = 1;
        p++;
    }
    
    while (*p >= '0' && *p <= '9') {
        num = num * 10 + (*p - '0');
        p++;
    }
    
    *pp = p;
    return neg ? -num : num;
}

/* Check if string starts with word */
static int starts_with(char* str, const char* word) {
    while (*word) {
        if (*str++ != *word++) return 0;
    }
    return (*str == ' ' || *str == '\\0' || *str == '\\t');
}

/* ═══════════════════════════════════════════════════════════════════════════
 * SCRIPT EXECUTOR
 * ═══════════════════════════════════════════════════════════════════════════ */

void run_script(char* code) {
    char* p = code;
    int a, b;
    
    vm_sp = 0;  /* Reset stack */
    vm_running = 1;
    
    kprint_color("\\n  EXECUTING: ", 0x0E);
    kprint(code);
    kprint("\\n");
    
    while (*p && vm_running) {
        p = skip_ws(p);
        if (!*p) break;
        
        /* ─────────────────────────────────────────────────────────────────
         * NUMBERS: Push to stack
         * ───────────────────────────────────────────────────────────────── */
        if ((*p >= '0' && *p <= '9') || (*p == '-' && p[1] >= '0' && p[1] <= '9')) {
            vm_push(parse_int(&p));
            continue;
        }
        
        /* ─────────────────────────────────────────────────────────────────
         * ARITHMETIC OPERATORS
         * ───────────────────────────────────────────────────────────────── */
        if (*p == '+' && (p[1] == ' ' || p[1] == '\\0')) {
            b = vm_pop(); a = vm_pop();
            vm_push(a + b);
            p++;
            continue;
        }
        if (*p == '-' && (p[1] == ' ' || p[1] == '\\0')) {
            b = vm_pop(); a = vm_pop();
            vm_push(a - b);
            p++;
            continue;
        }
        if (*p == '*') {
            b = vm_pop(); a = vm_pop();
            vm_push(a * b);
            p++;
            continue;
        }
        if (*p == '/') {
            b = vm_pop(); a = vm_pop();
            if (b == 0) {
                kprint_color("  Division by zero!\\n", 0x0C);
                vm_push(0);
            } else {
                vm_push(a / b);
            }
            p++;
            continue;
        }
        if (*p == '%') {
            b = vm_pop(); a = vm_pop();
            if (b == 0) {
                kprint_color("  Modulo by zero!\\n", 0x0C);
                vm_push(0);
            } else {
                vm_push(a % b);
            }
            p++;
            continue;
        }
        
        /* ─────────────────────────────────────────────────────────────────
         * COMPARISON OPERATORS
         * ───────────────────────────────────────────────────────────────── */
        if (*p == '=' && p[1] == '=') {
            b = vm_pop(); a = vm_pop();
            vm_push(a == b ? 1 : 0);
            p += 2;
            continue;
        }
        if (*p == '<') {
            b = vm_pop(); a = vm_pop();
            vm_push(a < b ? 1 : 0);
            p++;
            continue;
        }
        if (*p == '>') {
            b = vm_pop(); a = vm_pop();
            vm_push(a > b ? 1 : 0);
            p++;
            continue;
        }
        
        /* ─────────────────────────────────────────────────────────────────
         * STACK OPERATORS
         * ───────────────────────────────────────────────────────────────── */
        if (starts_with(p, "dup")) {
            vm_push(vm_peek());
            p += 3;
            continue;
        }
        if (starts_with(p, "drop")) {
            vm_pop();
            p += 4;
            continue;
        }
        if (starts_with(p, "swap")) {
            b = vm_pop(); a = vm_pop();
            vm_push(b); vm_push(a);
            p += 4;
            continue;
        }
        if (starts_with(p, "over")) {
            a = vm_stack[vm_sp - 2];
            vm_push(a);
            p += 4;
            continue;
        }
        if (starts_with(p, "rot")) {
            int c = vm_pop(); b = vm_pop(); a = vm_pop();
            vm_push(b); vm_push(c); vm_push(a);
            p += 3;
            continue;
        }
        
        /* ─────────────────────────────────────────────────────────────────
         * I/O OPERATORS
         * ───────────────────────────────────────────────────────────────── */
        if (*p == '.') {
            /* Print top of stack */
            a = vm_pop();
            kprint_color("  → ", 0x0A);
            kprint_int(a);
            kprint("\\n");
            p++;
            continue;
        }
        if (starts_with(p, "emit")) {
            /* Print as ASCII character */
            a = vm_pop();
            kputchar((char)a);
            p += 4;
            continue;
        }
        if (starts_with(p, "cr")) {
            /* Carriage return */
            kprint("\\n");
            p += 2;
            continue;
        }
        
        /* ─────────────────────────────────────────────────────────────────
         * VARIABLES (a-z)
         * ───────────────────────────────────────────────────────────────── */
        if (*p == '@' && p[1] >= 'a' && p[1] <= 'z') {
            /* Fetch variable */
            vm_push(vm_vars[p[1] - 'a']);
            p += 2;
            continue;
        }
        if (*p == '!' && p[1] >= 'a' && p[1] <= 'z') {
            /* Store to variable */
            vm_vars[p[1] - 'a'] = vm_pop();
            p += 2;
            continue;
        }
        
        /* ─────────────────────────────────────────────────────────────────
         * SPECIAL WORDS
         * ───────────────────────────────────────────────────────────────── */
        if (starts_with(p, "phi")) {
            /* Push phi * 1000000 (1618033) */
            vm_push(1618033);
            p += 3;
            continue;
        }
        if (starts_with(p, "depth")) {
            /* Push stack depth */
            vm_push(vm_sp);
            p += 5;
            continue;
        }
        if (starts_with(p, "clear")) {
            /* Clear stack */
            vm_sp = 0;
            p += 5;
            continue;
        }
        if (starts_with(p, "halt")) {
            vm_running = 0;
            p += 4;
            continue;
        }
        
        /* ─────────────────────────────────────────────────────────────────
         * SHOW STACK
         * ───────────────────────────────────────────────────────────────── */
        if (starts_with(p, ".s")) {
            kprint_color("  Stack: [", 0x0B);
            for (int i = 0; i < vm_sp; i++) {
                if (i > 0) kprint(" ");
                kprint_int(vm_stack[i]);
            }
            kprint("]\\n");
            p += 2;
            continue;
        }
        
        /* Unknown token - skip to next space */
        kprint_color("  Unknown: ", 0x0C);
        while (*p && *p != ' ' && *p != '\\t') {
            kputchar(*p++);
        }
        kprint("\\n");
    }
    
    /* Show final stack if not empty */
    if (vm_sp > 0) {
        kprint_color("  Stack: [", 0x0B);
        for (int i = 0; i < vm_sp; i++) {
            if (i > 0) kprint(" ");
            kprint_int(vm_stack[i]);
        }
        kprint("]\\n");
    }
    
    kprint("\\n");
}

/* ═══════════════════════════════════════════════════════════════════════════
 * HELP
 * ═══════════════════════════════════════════════════════════════════════════ */

void compiler_help(void) {
    kprint_color("\\n  FRAY-FORTH LANGUAGE REFERENCE\\n", 0x0E);
    kprint("  ────────────────────────────────────────\\n");
    kprint_color("  Arithmetic:\\n", 0x0B);
    kprint("    + - * / %    Basic operations\\n");
    kprint_color("  Stack:\\n", 0x0B);
    kprint("    dup          Duplicate top\\n");
    kprint("    drop         Discard top\\n");
    kprint("    swap         Swap top two\\n");
    kprint("    over         Copy second to top\\n");
    kprint("    rot          Rotate top three\\n");
    kprint_color("  I/O:\\n", 0x0B);
    kprint("    .            Print and pop\\n");
    kprint("    .s           Show stack\\n");
    kprint("    emit         Print as char\\n");
    kprint("    cr           Newline\\n");
    kprint_color("  Variables:\\n", 0x0B);
    kprint("    !x           Store to x (a-z)\\n");
    kprint("    @x           Fetch from x\\n");
    kprint_color("  Special:\\n", 0x0B);
    kprint("    phi          Push 1618033\\n");
    kprint("    depth        Push stack size\\n");
    kprint("    clear        Clear stack\\n");
    kprint("\\n");
}

#endif /* FRAY_COMPILER_C */
""";
        
        writeFile(OUTPUT_DIR + "/compiler.c", compiler);
    }

    private static void updateKernelWithCompiler() throws IOException {
        System.out.println("   [2/2] Generating kernel integration patch...");
        
        String patch = """
/* ═══════════════════════════════════════════════════════════════════════════
 * KERNEL INTEGRATION PATCH - Gen 143
 * 
 * Add this to your kernel.c to integrate the compiler:
 * 
 * 1. At the top of kernel.c, add:
 *    #include "compiler.c"
 * 
 * 2. In execute_command(), add this case:
 *    } else if (kstrncmp(cmd, "run ", 4) == 0) {
 *        run_script(cmd + 4);
 *    } else if (kstrcmp(cmd, "forth") == 0 || kstrcmp(cmd, "lang") == 0) {
 *        compiler_help();
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Example shell commands after integration:

   fray> run 10 5 + .
   EXECUTING: 10 5 + .
   → 15

   fray> run 3 dup * .
   EXECUTING: 3 dup * .
   → 9

   fray> run 100 !a 50 !b @a @b - .
   EXECUTING: 100 !a 50 !b @a @b - .
   → 50

   fray> run phi .
   EXECUTING: phi .
   → 1618033

   fray> forth
   FRAY-FORTH LANGUAGE REFERENCE
   ...
*/
""";
        
        writeFile(OUTPUT_DIR + "/compiler_patch.txt", patch);
    }

    private static void writeFile(String path, String content) throws IOException {
        Path filePath = Paths.get(path);
        Files.createDirectories(filePath.getParent());
        Files.writeString(filePath, content);
        System.out.println("      → " + path);
    }
}
