/**
 * Message Store
 * Generated by Fraynix Genesis Engine
 * Technology: PostgreSQL
 * Description: Message persistence
 */

-- Message persistence

CREATE TABLE IF NOT EXISTS data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data TEXT NOT NULL
);

CREATE INDEX idx_created_at ON data(created_at);

-- Sample data
INSERT INTO data (data) VALUES ('Genesis Engine initialized');
