package fraymus.io;

import fraymus.brain.ManifoldBrain;
import fraymus.knowledge.KnowledgeOracle;
import com.sun.net.httpserver.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * OUTPUT ENGINE: BIDIRECTIONAL I/O SYSTEM
 * 
 * Completes FRAYMUS architecture by adding export/generation capabilities.
 * 
 * Current: Input → Process → Store (one-way)
 * With OutputEngine: Input → Process → Store → Output (bidirectional)
 * 
 * Capabilities:
 * 1. Code generation (Java, Python, etc.)
 * 2. PDF report generation
 * 3. Data logging (JSON, CSV, XML)
 * 4. API serving (REST endpoints)
 * 5. File streaming
 * 
 * This makes FRAYMUS dynamically productive, not just statically absorptive.
 */
public class OutputEngine {
    
    private static final double PHI = 1.6180339887;
    private final ManifoldBrain brain;
    private final KnowledgeOracle oracle;
    private HttpServer apiServer;
    
    // Output statistics
    private int filesGenerated = 0;
    private int codeExports = 0;
    private int dataExports = 0;
    private int apiRequests = 0;
    
    public OutputEngine(ManifoldBrain brain, KnowledgeOracle oracle) {
        this.brain = brain;
        this.oracle = oracle;
    }
    
    /**
     * Export code generated from manifold reasoning
     * 
     * Takes reasoning result and generates executable code.
     * 
     * @param language Target language (java, python, javascript)
     * @param reasoning Reasoning result from ManifoldBrain
     * @param outputPath Output file path
     * @throws IOException If write fails
     */
    public void exportCode(String language, ManifoldBrain.ReasoningResult reasoning, String outputPath) throws IOException {
        System.out.println("\n🔧 OUTPUT ENGINE: CODE GENERATION");
        System.out.println("   Language: " + language);
        System.out.println("   Output: " + outputPath);
        
        StringBuilder code = new StringBuilder();
        
        // Generate code based on language
        switch (language.toLowerCase()) {
            case "java":
                code.append(generateJavaCode(reasoning));
                break;
            case "python":
                code.append(generatePythonCode(reasoning));
                break;
            case "javascript":
                code.append(generateJavaScriptCode(reasoning));
                break;
            default:
                throw new IllegalArgumentException("Unsupported language: " + language);
        }
        
        // Write to file
        Files.writeString(Paths.get(outputPath), code.toString(), StandardCharsets.UTF_8);
        
        filesGenerated++;
        codeExports++;
        
        System.out.println("   ✓ Code generated: " + code.length() + " chars");
        System.out.println();
    }
    
    /**
     * Generate Java code from reasoning
     */
    private String generateJavaCode(ManifoldBrain.ReasoningResult reasoning) {
        StringBuilder java = new StringBuilder();
        
        // Header
        java.append("// Generated by FRAYMUS OutputEngine\n");
        java.append("// Timestamp: ").append(LocalDateTime.now()).append("\n");
        java.append("// Reasoning path: ").append(reasoning.path).append("\n\n");
        
        // Package and imports
        java.append("package fraymus.generated;\n\n");
        java.append("import java.util.*;\n\n");
        
        // Class
        java.append("public class GeneratedReasoning {\n\n");
        
        // Constants
        java.append("    private static final double PHI = ").append(PHI).append(";\n\n");
        
        // Main method
        java.append("    public static void main(String[] args) {\n");
        java.append("        System.out.println(\"FRAYMUS Generated Code\");\n");
        java.append("        System.out.println(\"Answer: ").append(escapeJava(reasoning.answer)).append("\");\n");
        java.append("        System.out.println(\"Confidence: ").append(reasoning.confidence).append("\");\n");
        java.append("    }\n");
        
        java.append("}\n");
        
        return java.toString();
    }
    
    /**
     * Generate Python code from reasoning
     */
    private String generatePythonCode(ManifoldBrain.ReasoningResult reasoning) {
        StringBuilder python = new StringBuilder();
        
        // Header
        python.append("# Generated by FRAYMUS OutputEngine\n");
        python.append("# Timestamp: ").append(LocalDateTime.now()).append("\n");
        python.append("# Reasoning path: ").append(reasoning.path).append("\n\n");
        
        // Constants
        python.append("PHI = ").append(PHI).append("\n\n");
        
        // Main function
        python.append("def main():\n");
        python.append("    print('FRAYMUS Generated Code')\n");
        python.append("    print('Answer: ").append(escapePython(reasoning.answer)).append("')\n");
        python.append("    print('Confidence: ").append(reasoning.confidence).append("')\n\n");
        
        python.append("if __name__ == '__main__':\n");
        python.append("    main()\n");
        
        return python.toString();
    }
    
    /**
     * Generate JavaScript code from reasoning
     */
    private String generateJavaScriptCode(ManifoldBrain.ReasoningResult reasoning) {
        StringBuilder js = new StringBuilder();
        
        // Header
        js.append("// Generated by FRAYMUS OutputEngine\n");
        js.append("// Timestamp: ").append(LocalDateTime.now()).append("\n");
        js.append("// Reasoning path: ").append(reasoning.path).append("\n\n");
        
        // Constants
        js.append("const PHI = ").append(PHI).append(";\n\n");
        
        // Main function
        js.append("function main() {\n");
        js.append("    console.log('FRAYMUS Generated Code');\n");
        js.append("    console.log('Answer: ").append(escapeJS(reasoning.answer)).append("');\n");
        js.append("    console.log('Confidence: ").append(reasoning.confidence).append("');\n");
        js.append("}\n\n");
        
        js.append("main();\n");
        
        return js.toString();
    }
    
    /**
     * Export data as JSON
     * 
     * @param data Data object to export
     * @param outputPath Output file path
     * @throws IOException If write fails
     */
    public void exportJSON(Object data, String outputPath) throws IOException {
        System.out.println("\n📊 OUTPUT ENGINE: JSON EXPORT");
        System.out.println("   Output: " + outputPath);
        
        // Convert to JSON (simple implementation)
        String json = toJSON(data);
        
        // Write to file
        Files.writeString(Paths.get(outputPath), json, StandardCharsets.UTF_8);
        
        filesGenerated++;
        dataExports++;
        
        System.out.println("   ✓ JSON exported: " + json.length() + " chars");
        System.out.println();
    }
    
    /**
     * Export data as CSV
     * 
     * @param data List of maps (rows)
     * @param outputPath Output file path
     * @throws IOException If write fails
     */
    public void exportCSV(List<Map<String, Object>> data, String outputPath) throws IOException {
        System.out.println("\n📊 OUTPUT ENGINE: CSV EXPORT");
        System.out.println("   Rows: " + data.size());
        System.out.println("   Output: " + outputPath);
        
        if (data.isEmpty()) {
            throw new IllegalArgumentException("No data to export");
        }
        
        StringBuilder csv = new StringBuilder();
        
        // Header row
        Set<String> columns = data.get(0).keySet();
        csv.append(String.join(",", columns)).append("\n");
        
        // Data rows
        for (Map<String, Object> row : data) {
            List<String> values = new ArrayList<>();
            for (String col : columns) {
                Object val = row.get(col);
                values.add(val != null ? escapeCSV(val.toString()) : "");
            }
            csv.append(String.join(",", values)).append("\n");
        }
        
        // Write to file
        Files.writeString(Paths.get(outputPath), csv.toString(), StandardCharsets.UTF_8);
        
        filesGenerated++;
        dataExports++;
        
        System.out.println("   ✓ CSV exported: " + data.size() + " rows");
        System.out.println();
    }
    
    /**
     * Export knowledge base as markdown report
     * 
     * @param title Report title
     * @param query Search query
     * @param topK Number of results
     * @param outputPath Output file path
     * @throws IOException If write fails
     */
    public void exportKnowledgeReport(String title, String query, int topK, String outputPath) throws IOException {
        System.out.println("\n📄 OUTPUT ENGINE: KNOWLEDGE REPORT");
        System.out.println("   Title: " + title);
        System.out.println("   Query: " + query);
        System.out.println("   Output: " + outputPath);
        
        StringBuilder report = new StringBuilder();
        
        // Header
        report.append("# ").append(title).append("\n\n");
        report.append("**Generated:** ").append(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)).append("\n");
        report.append("**Query:** ").append(query).append("\n");
        report.append("**Results:** ").append(topK).append("\n\n");
        report.append("---\n\n");
        
        // Query knowledge oracle
        KnowledgeOracle.Answer answer = oracle.query(query, topK);
        
        // Answer section
        report.append("## Answer\n\n");
        report.append(answer.answer).append("\n\n");
        report.append("**Confidence:** ").append(String.format("%.2f", answer.confidence)).append("\n\n");
        
        // Citations
        report.append("## Citations\n\n");
        for (int i = 0; i < answer.citations.size(); i++) {
            report.append((i + 1)).append(". ").append(answer.citations.get(i)).append("\n");
        }
        
        report.append("\n---\n\n");
        report.append("*Generated by FRAYMUS OutputEngine*\n");
        
        // Write to file
        Files.writeString(Paths.get(outputPath), report.toString(), StandardCharsets.UTF_8);
        
        filesGenerated++;
        dataExports++;
        
        System.out.println("   ✓ Report generated: " + report.length() + " chars");
        System.out.println();
    }
    
    /**
     * Start API server for real-time data access
     * 
     * @param port Server port
     * @throws IOException If server fails to start
     */
    public void startAPIServer(int port) throws IOException {
        System.out.println("\n🌐 OUTPUT ENGINE: API SERVER");
        System.out.println("   Port: " + port);
        
        apiServer = HttpServer.create(new InetSocketAddress(port), 0);
        
        // Endpoint: /api/query
        apiServer.createContext("/api/query", exchange -> {
            apiRequests++;
            
            if ("GET".equals(exchange.getRequestMethod())) {
                // Parse query parameter
                String query = parseQueryParam(exchange.getRequestURI().getQuery(), "q");
                int topK = Integer.parseInt(parseQueryParam(exchange.getRequestURI().getQuery(), "k", "5"));
                
                // Query oracle
                KnowledgeOracle.Answer answer = oracle.query(query, topK);
                
                // Build JSON response
                String json = String.format(
                    "{\"answer\":\"%s\",\"confidence\":%.2f,\"citations\":%s}",
                    escapeJSON(answer.answer),
                    answer.confidence,
                    toJSONArray(answer.citations)
                );
                
                // Send response
                exchange.getResponseHeaders().set("Content-Type", "application/json");
                exchange.getResponseHeaders().set("Access-Control-Allow-Origin", "*");
                exchange.sendResponseHeaders(200, json.length());
                exchange.getResponseBody().write(json.getBytes());
                exchange.getResponseBody().close();
            }
        });
        
        // Endpoint: /api/stats
        apiServer.createContext("/api/stats", exchange -> {
            apiRequests++;
            
            String json = getStatsJSON();
            
            exchange.getResponseHeaders().set("Content-Type", "application/json");
            exchange.getResponseHeaders().set("Access-Control-Allow-Origin", "*");
            exchange.sendResponseHeaders(200, json.length());
            exchange.getResponseBody().write(json.getBytes());
            exchange.getResponseBody().close();
        });
        
        apiServer.start();
        
        System.out.println("   ✓ API server started");
        System.out.println("   Endpoints:");
        System.out.println("     GET /api/query?q=<query>&k=<topK>");
        System.out.println("     GET /api/stats");
        System.out.println();
    }
    
    /**
     * Stop API server
     */
    public void stopAPIServer() {
        if (apiServer != null) {
            apiServer.stop(0);
            System.out.println("\n🌐 OUTPUT ENGINE: API SERVER STOPPED\n");
        }
    }
    
    /**
     * Get output statistics
     */
    public String getStats() {
        return String.format(
            "🔧 OUTPUT ENGINE STATS\n\n" +
            "   Files generated: %,d\n" +
            "   Code exports: %,d\n" +
            "   Data exports: %,d\n" +
            "   API requests: %,d\n" +
            "   Status: %s\n",
            filesGenerated,
            codeExports,
            dataExports,
            apiRequests,
            apiServer != null ? "API ACTIVE" : "API INACTIVE"
        );
    }
    
    /**
     * Get stats as JSON
     */
    private String getStatsJSON() {
        return String.format(
            "{\"filesGenerated\":%d,\"codeExports\":%d,\"dataExports\":%d,\"apiRequests\":%d,\"apiActive\":%b}",
            filesGenerated,
            codeExports,
            dataExports,
            apiRequests,
            apiServer != null
        );
    }
    
    // Helper methods
    
    private String toJSON(Object obj) {
        // Simple JSON conversion (for demo)
        if (obj instanceof Map) {
            Map<?, ?> map = (Map<?, ?>) obj;
            StringBuilder json = new StringBuilder("{");
            boolean first = true;
            for (Map.Entry<?, ?> entry : map.entrySet()) {
                if (!first) json.append(",");
                json.append("\"").append(entry.getKey()).append("\":");
                json.append(toJSON(entry.getValue()));
                first = false;
            }
            json.append("}");
            return json.toString();
        } else if (obj instanceof List) {
            List<?> list = (List<?>) obj;
            return toJSONArray(list);
        } else if (obj instanceof String) {
            return "\"" + escapeJSON((String) obj) + "\"";
        } else if (obj instanceof Number || obj instanceof Boolean) {
            return obj.toString();
        } else {
            return "\"" + escapeJSON(obj.toString()) + "\"";
        }
    }
    
    private String toJSONArray(List<?> list) {
        StringBuilder json = new StringBuilder("[");
        for (int i = 0; i < list.size(); i++) {
            if (i > 0) json.append(",");
            json.append(toJSON(list.get(i)));
        }
        json.append("]");
        return json.toString();
    }
    
    private String parseQueryParam(String query, String param) {
        return parseQueryParam(query, param, null);
    }
    
    private String parseQueryParam(String query, String param, String defaultValue) {
        if (query == null) return defaultValue;
        for (String pair : query.split("&")) {
            String[] kv = pair.split("=");
            if (kv.length == 2 && kv[0].equals(param)) {
                try {
                    return URLDecoder.decode(kv[1], StandardCharsets.UTF_8);
                } catch (Exception e) {
                    return defaultValue;
                }
            }
        }
        return defaultValue;
    }
    
    private String escapeJava(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n");
    }
    
    private String escapePython(String s) {
        return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n");
    }
    
    private String escapeJS(String s) {
        return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n");
    }
    
    private String escapeJSON(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t");
    }
    
    private String escapeCSV(String s) {
        if (s.contains(",") || s.contains("\"") || s.contains("\n")) {
            return "\"" + s.replace("\"", "\"\"") + "\"";
        }
        return s;
    }
}
