;; ═══════════════════════════════════════════════════════════
;; FRAYNIX BOOTLOADER
;; Generated by Fraymus Agent Brain v3.0
;; φ^75 Validation Seal: 4721424167835376.00
;; ═══════════════════════════════════════════════════════════

bits 32
section .text

        ;; Multiboot Header (for GRUB compatibility)
        align 4
        dd 0x1BADB002              ; Magic number
        dd 0x00                    ; Flags
        dd - (0x1BADB002 + 0x00)   ; Checksum (must sum to 0)

global start
extern kmain

start:
  cli                   ; Clear interrupts (disable hardware interrupts)
  mov esp, stack_space  ; Set up stack pointer
  call kmain            ; Enter the C kernel
  hlt                   ; Halt CPU if kernel returns (should never happen)

section .bss
resb 8192               ; 8KB stack
stack_space:
