/* ═══════════════════════════════════════════════════════════ */
/* FRAY-C COMPILER & VIRTUAL MACHINE                           */
/* Stack-based bytecode interpreter                            */
/* Generated by Fraymus Agent Brain v3.0                       */
/* φ^75 Validation Seal: 4721424167835376.00                  */
/* ═══════════════════════════════════════════════════════════ */

/* Stack Machine State */
int stack[256];  /* Virtual stack */
int sp = 0;      /* Stack pointer */

/* Stack Operations */
void push(int val) {
    if(sp < 256) {
        stack[sp++] = val;
    }
}

int pop() {
    if(sp > 0) {
        return stack[--sp];
    }
    return 0;
}

/* Integer to String Conversion */
void int_to_str(int val, char* buf) {
    int j = 0;
    
    if(val == 0) {
        buf[j++] = '0';
        buf[j] = '\0';
        return;
    }
    
    /* Handle negative numbers */
    int is_negative = 0;
    if(val < 0) {
        is_negative = 1;
        val = -val;
    }
    
    /* Extract digits (reversed) */
    while(val > 0) {
        buf[j++] = (val % 10) + '0';
        val /= 10;
    }
    
    /* Add minus sign if negative */
    if(is_negative) {
        buf[j++] = '-';
    }
    
    buf[j] = '\0';
    
    /* Reverse string */
    int start = 0;
    int end = j - 1;
    while(start < end) {
        char t = buf[start];
        buf[start] = buf[end];
        buf[end] = t;
        start++;
        end--;
    }
}

/* ═══════════════════════════════════════════════════════════ */
/* SCRIPT INTERPRETER (Stack-Based VM)                         */
/* ═══════════════════════════════════════════════════════════ */

void run_script(char* code) {
    int i = 0;
    sp = 0;  /* Reset stack */
    
    kprint("[FrayC] Executing: ");
    kprint(code);
    kprint("\n");
    
    /* Parse and execute tokens */
    while(code[i] != '\0') {
        /* Skip whitespace */
        if(code[i] == ' ' || code[i] == '\t') {
            i++;
            continue;
        }
        
        /* NUMBER: Push to stack */
        if(code[i] >= '0' && code[i] <= '9') {
            int num = 0;
            while(code[i] >= '0' && code[i] <= '9') {
                num = num * 10 + (code[i] - '0');
                i++;
            }
            push(num);
            continue;
        }
        
        /* OPERATOR: Add */
        if(code[i] == '+') {
            int b = pop();
            int a = pop();
            push(a + b);
            kprint("  [ADD] ");
        }
        /* OPERATOR: Subtract */
        else if(code[i] == '-') {
            int b = pop();
            int a = pop();
            push(a - b);
            kprint("  [SUB] ");
        }
        /* OPERATOR: Multiply */
        else if(code[i] == '*') {
            int b = pop();
            int a = pop();
            push(a * b);
            kprint("  [MUL] ");
        }
        /* OPERATOR: Divide */
        else if(code[i] == '/') {
            int b = pop();
            int a = pop();
            if(b != 0) {
                push(a / b);
                kprint("  [DIV] ");
            } else {
                kprint("  [ERROR: Division by zero] ");
                return;
            }
        }
        /* OPERATOR: Print (.) */
        else if(code[i] == '.') {
            int val = pop();
            char buf[16];
            int_to_str(val, buf);
            
            kprint("\n  > OUTPUT: ");
            kprint(buf);
            kprint("\n");
        }
        /* OPERATOR: Duplicate (dup) */
        else if(code[i] == 'd' && code[i+1] == 'u' && code[i+2] == 'p') {
            if(sp > 0) {
                int val = stack[sp-1];
                push(val);
                kprint("  [DUP] ");
            }
            i += 2;  /* Skip 'up' */
        }
        /* OPERATOR: Swap */
        else if(code[i] == 's' && code[i+1] == 'w' && code[i+2] == 'a' && code[i+3] == 'p') {
            if(sp >= 2) {
                int b = pop();
                int a = pop();
                push(b);
                push(a);
                kprint("  [SWAP] ");
            }
            i += 3;  /* Skip 'wap' */
        }
        
        i++;
    }
    
    kprint("[FrayC] Execution complete.\n");
}
