#!/bin/bash
# Fraynix Kernel Compilation Script
# Generated by Fraymus Agent Brain v3.0

echo "═══════════════════════════════════════════════════════════"
echo "  🐧 COMPILING FRAYNIX KERNEL"
echo "═══════════════════════════════════════════════════════════"

echo "[1/4] Assembling bootloader..."
nasm -f elf32 boot.asm -o boot.o
if [ $? -ne 0 ]; then echo "❌ Assembly failed"; exit 1; fi

echo "[2/4] Compiling kernel..."
gcc -m32 -c kernel.c -o kernel.o -ffreestanding -nostdlib
if [ $? -ne 0 ]; then echo "❌ Compilation failed"; exit 1; fi

echo "[3/4] Linking..."
ld -m elf_i386 -T linker.ld -o fraynix_kernel boot.o kernel.o
if [ $? -ne 0 ]; then echo "❌ Linking failed"; exit 1; fi

echo "[4/4] Kernel built successfully!"
echo "✅ fraynix_kernel is ready"

echo "To run in QEMU:"
echo "  qemu-system-i386 -kernel fraynix_kernel"

echo "To run automatically:"
read -p "Launch in QEMU now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    qemu-system-i386 -kernel fraynix_kernel
fi
