@echo off
REM Fraynix Kernel Compilation Script (Windows)
REM Generated by Fraymus Agent Brain v3.0
REM Requires: WSL, MinGW, or Cygwin with nasm, gcc, ld

echo ═══════════════════════════════════════════════════════════
echo   🐧 COMPILING FRAYNIX KERNEL
echo ═══════════════════════════════════════════════════════════

echo [1/4] Assembling bootloader...
nasm -f elf32 boot.asm -o boot.o
if %ERRORLEVEL% NEQ 0 (echo ❌ Assembly failed & exit /b 1)

echo [2/4] Compiling kernel...
gcc -m32 -c kernel.c -o kernel.o -ffreestanding -nostdlib
if %ERRORLEVEL% NEQ 0 (echo ❌ Compilation failed & exit /b 1)

echo [3/4] Linking...
ld -m elf_i386 -T linker.ld -o fraynix_kernel boot.o kernel.o
if %ERRORLEVEL% NEQ 0 (echo ❌ Linking failed & exit /b 1)

echo [4/4] Kernel built successfully!
echo ✅ fraynix_kernel is ready

echo To run in QEMU:
echo   qemu-system-i386 -kernel fraynix_kernel
pause
