/* ═══════════════════════════════════════════════════════════ */
/* FRAY-GPU: SOFTWARE RASTERIZER                               */
/* Pure C Linear Algebra - No Hardware GPU Required            */
/* Generated by Fraymus Agent Brain v3.0                       */
/* φ^75 Validation Seal: 4721424167835376.00                  */
/* ═══════════════════════════════════════════════════════════ */

/* ═══════════════════════════════════════════════════════════ */
/* DATA STRUCTURES                                              */
/* ═══════════════════════════════════════════════════════════ */

/* 3D Vector */
typedef struct {
    float x, y, z;
} Vec3;

/* 2D Point (screen coordinates) */
typedef struct {
    int x, y;
} Point2D;

/* ═══════════════════════════════════════════════════════════ */
/* MATH UTILITIES (Fixed-Point Approximations)                 */
/* ═══════════════════════════════════════════════════════════ */

/* Fast sine approximation (Taylor series) */
float fast_sin(float x) {
    /* Normalize to -π to π */
    while(x > 3.14159f) x -= 6.28318f;
    while(x < -3.14159f) x += 6.28318f;
    
    /* Taylor series: sin(x) ≈ x - x³/6 + x⁵/120 */
    float x2 = x * x;
    float x3 = x2 * x;
    float x5 = x3 * x2;
    return x - (x3 / 6.0f) + (x5 / 120.0f);
}

/* Fast cosine approximation */
float fast_cos(float x) {
    return fast_sin(x + 1.5708f);  /* cos(x) = sin(x + π/2) */
}

/* ═══════════════════════════════════════════════════════════ */
/* VERTEX SHADER (3D Transformations)                          */
/* ═══════════════════════════════════════════════════════════ */

/* Rotate point around Y axis */
Vec3 rotateY(Vec3 p, float theta) {
    Vec3 out;
    float c = fast_cos(theta);
    float s = fast_sin(theta);
    
    out.x = p.x * c - p.z * s;
    out.y = p.y;
    out.z = p.x * s + p.z * c;
    return out;
}

/* Rotate point around X axis */
Vec3 rotateX(Vec3 p, float theta) {
    Vec3 out;
    float c = fast_cos(theta);
    float s = fast_sin(theta);
    
    out.x = p.x;
    out.y = p.y * c - p.z * s;
    out.z = p.y * s + p.z * c;
    return out;
}

/* Rotate point around Z axis */
Vec3 rotateZ(Vec3 p, float theta) {
    Vec3 out;
    float c = fast_cos(theta);
    float s = fast_sin(theta);
    
    out.x = p.x * c - p.y * s;
    out.y = p.x * s + p.y * c;
    out.z = p.z;
    return out;
}

/* ═══════════════════════════════════════════════════════════ */
/* PROJECTION (3D → 2D)                                         */
/* ═══════════════════════════════════════════════════════════ */

/* Perspective projection */
Point2D project(Vec3 p) {
    Point2D out;
    float fov = 128.0f;              /* Field of view */
    float viewer_distance = 4.0f;    /* Camera distance */
    
    /* Perspective divide: x' = x / z, y' = y / z */
    float z_factor = fov / (viewer_distance - p.z);
    
    /* Project and center on screen */
    out.x = (int)(p.x * z_factor) + 160;  /* Center X (320/2) */
    out.y = (int)(p.y * z_factor) + 100;  /* Center Y (200/2) */
    
    return out;
}

/* ═══════════════════════════════════════════════════════════ */
/* RASTERIZER (Line Drawing)                                    */
/* ═══════════════════════════════════════════════════════════ */

/* Bresenham's line algorithm */
void draw_line(int x0, int y0, int x1, int y1, unsigned char color) {
    int dx = x1 - x0;
    int dy = y1 - y0;
    
    if(dx < 0) dx = -dx;
    if(dy < 0) dy = -dy;
    
    int sx = (x0 < x1) ? 1 : -1;
    int sy = (y0 < y1) ? 1 : -1;
    int err = dx - dy;
    
    while(1) {
        put_pixel(x0, y0, color);
        
        if(x0 == x1 && y0 == y1) break;
        
        int e2 = 2 * err;
        if(e2 > -dy) {
            err -= dy;
            x0 += sx;
        }
        if(e2 < dx) {
            err += dx;
            y0 += sy;
        }
    }
}

/* ═══════════════════════════════════════════════════════════ */
/* 3D OBJECT RENDERING                                          */
/* ═══════════════════════════════════════════════════════════ */

/* Render a rotating cube */
void gpu_render_frame(float time) {
    /* Clear screen to black */
    for(int i = 0; i < 320 * 200; i++) {
        vga_mem[i] = 0;
    }
    
    /* Define cube vertices (8 corners) */
    Vec3 cube[8] = {
        {-1, -1, -1},  /* 0: Back bottom left */
        { 1, -1, -1},  /* 1: Back bottom right */
        { 1,  1, -1},  /* 2: Back top right */
        {-1,  1, -1},  /* 3: Back top left */
        {-1, -1,  1},  /* 4: Front bottom left */
        { 1, -1,  1},  /* 5: Front bottom right */
        { 1,  1,  1},  /* 6: Front top right */
        {-1,  1,  1}   /* 7: Front top left */
    };
    
    /* Vertex shader: Transform and project */
    Point2D screen[8];
    for(int i = 0; i < 8; i++) {
        /* Apply rotations */
        Vec3 rotated = rotateY(cube[i], time);
        rotated = rotateX(rotated, time * 0.7f);
        
        /* Project to 2D */
        screen[i] = project(rotated);
    }
    
    /* Rasterizer: Draw edges (wireframe) */
    unsigned char color = 15;  /* White */
    
    /* Back face */
    draw_line(screen[0].x, screen[0].y, screen[1].x, screen[1].y, color);
    draw_line(screen[1].x, screen[1].y, screen[2].x, screen[2].y, color);
    draw_line(screen[2].x, screen[2].y, screen[3].x, screen[3].y, color);
    draw_line(screen[3].x, screen[3].y, screen[0].x, screen[0].y, color);
    
    /* Front face */
    draw_line(screen[4].x, screen[4].y, screen[5].x, screen[5].y, color);
    draw_line(screen[5].x, screen[5].y, screen[6].x, screen[6].y, color);
    draw_line(screen[6].x, screen[6].y, screen[7].x, screen[7].y, color);
    draw_line(screen[7].x, screen[7].y, screen[4].x, screen[4].y, color);
    
    /* Connecting edges */
    draw_line(screen[0].x, screen[0].y, screen[4].x, screen[4].y, color);
    draw_line(screen[1].x, screen[1].y, screen[5].x, screen[5].y, color);
    draw_line(screen[2].x, screen[2].y, screen[6].x, screen[6].y, color);
    draw_line(screen[3].x, screen[3].y, screen[7].x, screen[7].y, color);
}

/* Render spinning phi spiral */
void gpu_render_phi_spiral(float time) {
    /* Clear screen */
    for(int i = 0; i < 320 * 200; i++) {
        vga_mem[i] = 0;
    }
    
    /* Golden ratio */
    float phi = 1.618f;
    
    /* Draw spiral */
    for(int i = 0; i < 50; i++) {
        float angle = i * 0.5f + time;
        float radius = i * 0.1f * phi;
        
        Vec3 p;
        p.x = fast_cos(angle) * radius;
        p.y = fast_sin(angle) * radius;
        p.z = i * 0.05f;
        
        p = rotateY(p, time * 0.5f);
        Point2D screen = project(p);
        
        unsigned char color = 10 + (i % 6);
        draw_circle(screen.x, screen.y, 2, color);
    }
}
