/* ═══════════════════════════════════════════════════════════ */
/* FRAY-GUI: THE WINDOW MANAGER                                */
/* Style: Cyber-Gold (Black, Gold, Glass)                      */
/* Generated by Fraymus Agent Brain v3.0                       */
/* φ^75 Validation Seal: 4721424167835376.00                  */
/* ═══════════════════════════════════════════════════════════ */

/* ═══════════════════════════════════════════════════════════ */
/* MOUSE DRIVER (PS/2)                                          */
/* ═══════════════════════════════════════════════════════════ */

/* Mouse state */
int mouse_x = 160;
int mouse_y = 100;
int mouse_buttons = 0;  /* Bit 0: Left, Bit 1: Right, Bit 2: Middle */
int mouse_byte_cycle = 0;
unsigned char mouse_bytes[3];

/* Initialize PS/2 mouse */
void init_mouse() {
    /* Enable auxiliary device */
    outb(0x64, 0xA8);
    
    /* Enable interrupts */
    outb(0x64, 0x20);
    unsigned char status = inb(0x60) | 2;
    outb(0x64, 0x60);
    outb(0x60, status);
    
    /* Set defaults */
    outb(0x64, 0xD4);
    outb(0x60, 0xF6);
    inb(0x60);  /* Acknowledge */
    
    /* Enable data reporting */
    outb(0x64, 0xD4);
    outb(0x60, 0xF4);
    inb(0x60);  /* Acknowledge */
    
    kprint("[FrayGUI] Mouse initialized\n");
}

/* Handle mouse interrupt (IRQ 12) */
void handle_mouse_interrupt() {
    unsigned char status = inb(0x64);
    if(!(status & 1)) return;
    
    unsigned char val = inb(0x60);
    
    /* PS/2 mouse sends 3-byte packets */
    mouse_bytes[mouse_byte_cycle++] = val;
    
    if(mouse_byte_cycle == 3) {
        mouse_byte_cycle = 0;
        
        /* Parse packet */
        mouse_buttons = mouse_bytes[0] & 0x07;
        
        /* X movement (signed) */
        int dx = mouse_bytes[1];
        if(mouse_bytes[0] & 0x10) dx |= 0xFFFFFF00;  /* Sign extend */
        
        /* Y movement (signed, inverted) */
        int dy = mouse_bytes[2];
        if(mouse_bytes[0] & 0x20) dy |= 0xFFFFFF00;  /* Sign extend */
        
        /* Update position */
        mouse_x += dx;
        mouse_y -= dy;  /* Invert Y */
        
        /* Clamp to screen */
        if(mouse_x < 0) mouse_x = 0;
        if(mouse_x > 319) mouse_x = 319;
        if(mouse_y < 0) mouse_y = 0;
        if(mouse_y > 199) mouse_y = 199;
    }
}

/* ═══════════════════════════════════════════════════════════ */
/* THEME ENGINE (Cyber-Gold)                                    */
/* ═══════════════════════════════════════════════════════════ */

/* Color palette */
#define COLOR_BLACK     0
#define COLOR_BLUE      1
#define COLOR_GREEN     2
#define COLOR_RED       4
#define COLOR_GOLD      14
#define COLOR_WHITE     15
#define COLOR_OBSIDIAN  8   /* Dark gray */
#define COLOR_SILVER    7   /* Light gray */

/* Draw window with title bar and shadow */
void draw_window(int x, int y, int w, int h, const char* title) {
    /* 1. Drop shadow (offset 2 pixels) */
    draw_rect(x + 2, y + 2, w, h, COLOR_BLACK);
    
    /* 2. Window body (obsidian) */
    draw_rect(x, y, w, h, COLOR_OBSIDIAN);
    
    /* 3. Title bar (gold) */
    draw_rect(x, y, w, 12, COLOR_GOLD);
    
    /* 4. Title text (would render font here) */
    /* draw_string(x + 4, y + 2, title, COLOR_BLACK); */
    
    /* 5. Close button [X] (red) */
    draw_rect(x + w - 10, y + 2, 8, 8, COLOR_RED);
    
    /* 6. Window border (lighter) */
    draw_hline(x, x + w - 1, y, COLOR_SILVER);
    draw_vline(x, y, y + h - 1, COLOR_SILVER);
    draw_hline(x, x + w - 1, y + h - 1, COLOR_SILVER);
    draw_vline(x + w - 1, y, y + h - 1, COLOR_SILVER);
}

/* Draw desktop icon */
void draw_icon(int x, int y, const char* name, unsigned char color) {
    /* Icon background */
    draw_rect(x, y, 32, 32, color);
    
    /* Icon border */
    draw_rect(x, y, 32, 32, COLOR_WHITE);  /* Would be hollow rect */
    
    /* Label (would render text below icon) */
    /* draw_string(x, y + 34, name, COLOR_WHITE); */
}

/* Draw mouse cursor */
void draw_cursor() {
    /* Simple arrow cursor (5x5) */
    put_pixel(mouse_x, mouse_y, COLOR_WHITE);
    put_pixel(mouse_x + 1, mouse_y + 1, COLOR_WHITE);
    put_pixel(mouse_x + 2, mouse_y + 2, COLOR_WHITE);
    put_pixel(mouse_x + 3, mouse_y + 3, COLOR_WHITE);
    put_pixel(mouse_x, mouse_y + 1, COLOR_WHITE);
    put_pixel(mouse_x, mouse_y + 2, COLOR_WHITE);
    put_pixel(mouse_x + 1, mouse_y + 2, COLOR_WHITE);
}

/* ═══════════════════════════════════════════════════════════ */
/* EVENT SYSTEM                                                 */
/* ═══════════════════════════════════════════════════════════ */

/* Check if point is inside rectangle */
int point_in_rect(int px, int py, int rx, int ry, int rw, int rh) {
    return (px >= rx && px < rx + rw && py >= ry && py < ry + rh);
}

/* Icon positions */
#define ICON_DOOM_X  20
#define ICON_DOOM_Y  20
#define ICON_NET_X   20
#define ICON_NET_Y   60
#define ICON_CODE_X  20
#define ICON_CODE_Y  100
#define ICON_SIZE    32

/* Handle click events */
void handle_click() {
    /* Check if DOOM icon clicked */
    if(point_in_rect(mouse_x, mouse_y, ICON_DOOM_X, ICON_DOOM_Y, ICON_SIZE, ICON_SIZE)) {
        kprint("[FrayGUI] Launching DOOM...\n");
        doom_loop();  /* Launch game */
        return;
    }
    
    /* Check if NET icon clicked */
    if(point_in_rect(mouse_x, mouse_y, ICON_NET_X, ICON_NET_Y, ICON_SIZE, ICON_SIZE)) {
        kprint("[FrayGUI] Opening Network Monitor...\n");
        /* Would open network app */
        return;
    }
    
    /* Check if CODE icon clicked */
    if(point_in_rect(mouse_x, mouse_y, ICON_CODE_X, ICON_CODE_Y, ICON_SIZE, ICON_SIZE)) {
        kprint("[FrayGUI] Opening FrayC Compiler...\n");
        /* Would open compiler window */
        return;
    }
}

/* ═══════════════════════════════════════════════════════════ */
/* DESKTOP MAIN LOOP                                            */
/* ═══════════════════════════════════════════════════════════ */

void start_desktop() {
    /* Initialize subsystems */
    init_vga();
    init_mouse();
    
    kprint("[FrayGUI] Desktop environment started\n");
    kprint("[FrayGUI] Theme: Cyber-Gold\n");
    
    int last_buttons = 0;
    
    while(1) {
        /* 1. DRAW BACKGROUND (Wallpaper) */
        draw_rect(0, 0, 320, 200, COLOR_BLUE);  /* Deep blue */
        
        /* 2. DRAW TASKBAR (Bottom) */
        draw_rect(0, 185, 320, 15, COLOR_SILVER);
        
        /* Start button (Gold) */
        draw_rect(2, 187, 50, 11, COLOR_GOLD);
        
        /* System tray area */
        draw_rect(270, 187, 48, 11, COLOR_OBSIDIAN);
        
        /* 3. DRAW DESKTOP ICONS */
        draw_icon(ICON_DOOM_X, ICON_DOOM_Y, "DOOM", COLOR_RED);
        draw_icon(ICON_NET_X, ICON_NET_Y, "NET", COLOR_GREEN);
        draw_icon(ICON_CODE_X, ICON_CODE_Y, "CODE", COLOR_WHITE);
        
        /* 4. DRAW ACTIVE WINDOWS */
        /* Example: Terminal window */
        draw_window(80, 40, 160, 120, "FrayTerminal");
        
        /* Window content area */
        draw_rect(82, 54, 156, 104, COLOR_BLACK);
        
        /* 5. UPDATE MOUSE */
        handle_mouse_interrupt();
        
        /* 6. HANDLE CLICKS */
        if((mouse_buttons & 1) && !(last_buttons & 1)) {
            /* Left button pressed (rising edge) */
            handle_click();
        }
        last_buttons = mouse_buttons;
        
        /* 7. DRAW CURSOR (Always on top) */
        draw_cursor();
        
        /* Frame delay */
        for(volatile int i = 0; i < 50000; i++);
    }
}

/* Launch desktop from kernel */
void gui_init() {
    kprint("[FrayGUI] Initializing desktop environment...\n");
    start_desktop();
}
