/* ═══════════════════════════════════════════════════════════ */
/* FRAYNIX KERNEL v2.0 (with FrayFS support)                  */
/* Generated by Fraymus Agent Brain v3.0                       */
/* φ^75 Validation Seal: 4721424167835376.00                  */
/* ═══════════════════════════════════════════════════════════ */

/* FrayFS Header Structure */
struct FrayHeader {
    char magic[4];           /* Offset 0-3:   "FRAY" */
    char name[32];           /* Offset 4-35:  Filename */
    unsigned int size;       /* Offset 36-39: File size */
    char padding[24];        /* Offset 40-63: Reserved */
};

/* Global video pointer */
char *vidptr = (char*)0xb8000;
unsigned int cursor_pos = 0;

/* Print string to screen */
void kprint(const char *str) {
    unsigned int i = 0;
    while(str[i] != '\0') {
        vidptr[cursor_pos] = str[i];
        vidptr[cursor_pos + 1] = 0x0A;  /* Light green */
        cursor_pos += 2;
        i++;
    }
}

/* Print newline */
void knewline() {
    cursor_pos = ((cursor_pos / 160) + 1) * 160;
}

/* Read FrayFS filesystem from disk */
void read_filesystem(char* disk_address) {
    struct FrayHeader* header = (struct FrayHeader*)disk_address;
    
    kprint("[FrayFS] Scanning disk...");
    knewline();
    
    int file_count = 0;
    
    /* Iterate through linked list of files */
    while(header->magic[0] == 'F' && 
          header->magic[1] == 'R' && 
          header->magic[2] == 'A' && 
          header->magic[3] == 'Y') {
        
        /* Found a file */
        kprint("[FrayFS] Found: ");
        kprint(header->name);
        knewline();
        
        file_count++;
        
        /* Jump to next file: Current + Header (64) + Data Size */
        char* next_addr = (char*)header + 64 + header->size;
        header = (struct FrayHeader*)next_addr;
    }
    
    kprint("[FrayFS] Scan complete.");
    knewline();
}

/* Kernel Main Entry Point */
void kmain(void) {
    unsigned int j = 0;

    /* Clear Screen (80x25 text mode, 2 bytes per char) */
    while(j < 80 * 25 * 2) {
        vidptr[j] = ' ';      /* Character */
        vidptr[j+1] = 0x07;   /* Light gray on black */
        j = j + 2;
    }

    cursor_pos = 0;

    /* Boot Message */
    kprint("FRAYMUS HAS AWAKENED - RING 0 ACCESS GRANTED");
    knewline();
    kprint("Fraynix Kernel v2.0 (with FrayFS)");
    knewline();
    knewline();

    /* Read filesystem (disk loaded at 0x200000 by bootloader) */
    /* Note: In real implementation, bootloader would load disk */
    /* For now, this is a placeholder showing the structure */
    /* read_filesystem((char*)0x200000); */

    kprint("System ready. Entering idle loop...");
    knewline();

    /* Infinite loop - kernel never exits */
    while(1) {
        /* Halt CPU until next interrupt */
        __asm__("hlt");
    }
}
