/* ═══════════════════════════════════════════════════════════ */
/* FRAY SOLAR SYSTEM: N-BODY GRAVITY SIMULATOR                 */
/* Real planetary data with Newtonian physics                  */
/* Generated by Fraymus Agent Brain v3.0                       */
/* φ^75 Validation Seal: 4721424167835376.00                  */
/* ═══════════════════════════════════════════════════════════ */

#include <math.h>

/* ═══════════════════════════════════════════════════════════ */
/* PHYSICAL CONSTANTS                                           */
/* ═══════════════════════════════════════════════════════════ */

/* Gravitational constant (scaled for simulation) */
#define G 6.674e-11
/* Astronomical Unit (Earth-Sun distance in meters) */
#define AU 1.496e11
/* Time step (1 day in seconds) */
#define DT 86400.0
/* Simulation speed multiplier */
float time_scale = 1.0;
int paused = 0;

/* ═══════════════════════════════════════════════════════════ */
/* DATA STRUCTURES                                              */
/* ═══════════════════════════════════════════════════════════ */

typedef struct {
    float x, y, z;     /* Position (meters) */
    float vx, vy, vz;  /* Velocity (m/s) */
    float ax, ay, az;  /* Acceleration (m/s²) */
    float mass;        /* Mass (kg) */
    float radius;      /* Visual radius (scaled) */
    unsigned char r, g, b; /* Color */
    char name[16];     /* Planet name */
} Body;

#define NUM_BODIES 9
Body bodies[NUM_BODIES];

/* ═══════════════════════════════════════════════════════════ */
/* PLANETARY DATA (Real astronomical values)                   */
/* ═══════════════════════════════════════════════════════════ */

void init_solar_system() {
    /* Sun */
    bodies[0] = (Body){
        0, 0, 0,                    /* Position at origin */
        0, 0, 0,                    /* Stationary */
        0, 0, 0,                    /* No initial acceleration */
        1.989e30,                   /* Mass: 1.989×10³⁰ kg */
        20.0,                       /* Visual radius */
        255, 200, 0,                /* Yellow */
        "Sun"
    };
    
    /* Mercury */
    bodies[1] = (Body){
        0.387 * AU, 0, 0,           /* 0.387 AU from Sun */
        0, 47870, 0,                /* Orbital velocity: 47.87 km/s */
        0, 0, 0,
        3.301e23,                   /* Mass */
        3.0,
        169, 169, 169,              /* Gray */
        "Mercury"
    };
    
    /* Venus */
    bodies[2] = (Body){
        0.723 * AU, 0, 0,
        0, 35020, 0,                /* 35.02 km/s */
        0, 0, 0,
        4.867e24,
        6.0,
        255, 198, 73,               /* Orange */
        "Venus"
    };
    
    /* Earth */
    bodies[3] = (Body){
        1.0 * AU, 0, 0,
        0, 29780, 0,                /* 29.78 km/s */
        0, 0, 0,
        5.972e24,
        6.0,
        100, 149, 237,              /* Blue */
        "Earth"
    };
    
    /* Mars */
    bodies[4] = (Body){
        1.524 * AU, 0, 0,
        0, 24070, 0,                /* 24.07 km/s */
        0, 0, 0,
        6.417e23,
        4.0,
        193, 68, 14,                /* Red */
        "Mars"
    };
    
    /* Jupiter */
    bodies[5] = (Body){
        5.203 * AU, 0, 0,
        0, 13070, 0,                /* 13.07 km/s */
        0, 0, 0,
        1.898e27,
        12.0,
        201, 176, 55,               /* Tan */
        "Jupiter"
    };
    
    /* Saturn */
    bodies[6] = (Body){
        9.537 * AU, 0, 0,
        0, 9690, 0,                 /* 9.69 km/s */
        0, 0, 0,
        5.683e26,
        10.0,
        250, 232, 107,              /* Pale yellow */
        "Saturn"
    };
    
    /* Uranus */
    bodies[7] = (Body){
        19.191 * AU, 0, 0,
        0, 6810, 0,                 /* 6.81 km/s */
        0, 0, 0,
        8.681e25,
        8.0,
        79, 208, 231,               /* Cyan */
        "Uranus"
    };
    
    /* Neptune */
    bodies[8] = (Body){
        30.069 * AU, 0, 0,
        0, 5430, 0,                 /* 5.43 km/s */
        0, 0, 0,
        1.024e26,
        8.0,
        63, 84, 186,                /* Blue */
        "Neptune"
    };
}

/* ═══════════════════════════════════════════════════════════ */
/* GRAVITY CALCULATIONS                                         */
/* ═══════════════════════════════════════════════════════════ */

/* Calculate gravitational force between two bodies */
void calculate_gravity() {
    /* Reset accelerations */
    for(int i = 0; i < NUM_BODIES; i++) {
        bodies[i].ax = 0;
        bodies[i].ay = 0;
        bodies[i].az = 0;
    }
    
    /* Calculate pairwise gravitational forces */
    for(int i = 0; i < NUM_BODIES; i++) {
        for(int j = i + 1; j < NUM_BODIES; j++) {
            /* Distance vector */
            float dx = bodies[j].x - bodies[i].x;
            float dy = bodies[j].y - bodies[i].y;
            float dz = bodies[j].z - bodies[i].z;
            
            /* Distance magnitude */
            float r2 = dx*dx + dy*dy + dz*dz;
            float r = fast_sqrt(r2);
            
            /* Avoid division by zero */
            if(r < 1e6) r = 1e6;
            
            /* Newton's law: F = G * (m1 * m2) / r² */
            float force = G * bodies[i].mass * bodies[j].mass / r2;
            
            /* Force components (unit vector * force) */
            float fx = (dx / r) * force;
            float fy = (dy / r) * force;
            float fz = (dz / r) * force;
            
            /* Apply to both bodies (Newton's 3rd law) */
            bodies[i].ax += fx / bodies[i].mass;
            bodies[i].ay += fy / bodies[i].mass;
            bodies[i].az += fz / bodies[i].mass;
            
            bodies[j].ax -= fx / bodies[j].mass;
            bodies[j].ay -= fy / bodies[j].mass;
            bodies[j].az -= fz / bodies[j].mass;
        }
    }
}

/* ═══════════════════════════════════════════════════════════ */
/* INTEGRATION (Verlet method for stability)                   */
/* ═══════════════════════════════════════════════════════════ */

void update_positions() {
    if(paused) return;
    
    float dt = DT * time_scale;
    
    for(int i = 0; i < NUM_BODIES; i++) {
        /* Verlet integration: x(t+dt) = x(t) + v(t)*dt + 0.5*a(t)*dt² */
        bodies[i].x += bodies[i].vx * dt + 0.5 * bodies[i].ax * dt * dt;
        bodies[i].y += bodies[i].vy * dt + 0.5 * bodies[i].ay * dt * dt;
        bodies[i].z += bodies[i].vz * dt + 0.5 * bodies[i].az * dt * dt;
        
        /* Update velocity: v(t+dt) = v(t) + a(t)*dt */
        bodies[i].vx += bodies[i].ax * dt;
        bodies[i].vy += bodies[i].ay * dt;
        bodies[i].vz += bodies[i].az * dt;
    }
}

/* ═══════════════════════════════════════════════════════════ */
/* 3D VISUALIZATION                                             */
/* ═══════════════════════════════════════════════════════════ */

void render_solar_system() {
    clear_screen();
    
    /* Camera setup (view from above) */
    float cam_distance = 50.0 * AU;
    float cam_angle = 0.5; /* Slight tilt */
    
    /* Draw each body */
    for(int i = 0; i < NUM_BODIES; i++) {
        /* Scale position for display (1 AU = 100 pixels) */
        float scale = 100.0 / AU;
        int screen_x = 160 + (int)(bodies[i].x * scale);
        int screen_y = 100 - (int)(bodies[i].y * scale);
        
        /* Draw planet as filled circle */
        draw_filled_circle(screen_x, screen_y, (int)bodies[i].radius, 
                          bodies[i].r, bodies[i].g, bodies[i].b);
        
        /* Draw label */
        draw_string(screen_x + 5, screen_y - 10, bodies[i].name, 15);
        
        /* Draw distance from Sun (in AU) */
        if(i > 0) {
            float dx = bodies[i].x - bodies[0].x;
            float dy = bodies[i].y - bodies[0].y;
            float dz = bodies[i].z - bodies[0].z;
            float dist_au = fast_sqrt(dx*dx + dy*dy + dz*dz) / AU;
            
            char dist_str[32];
            sprintf(dist_str, "%.2f AU", dist_au);
            draw_string(screen_x + 5, screen_y + 5, dist_str, 14);
        }
    }
    
    /* Status info */
    draw_string(10, 10, "SOLAR SYSTEM SIMULATOR", 15);
    char status[64];
    sprintf(status, "Speed: %.1fx  %s", time_scale, paused ? "[PAUSED]" : "");
    draw_string(10, 20, status, 14);
    
    /* Controls */
    draw_string(10, 180, "[SPACE] Pause  [+/-] Speed  [R] Reset  [ESC] Exit", 14);
}

/* ═══════════════════════════════════════════════════════════ */
/* MAIN SIMULATION LOOP                                         */
/* ═══════════════════════════════════════════════════════════ */

void run_solar_system() {
    kprint("[UNIVERSE] Initializing solar system...\n");
    
    init_solar_system();
    init_vga();
    
    kprint("[UNIVERSE] Simulation started\n");
    kprint("  Bodies: 9 (Sun + 8 planets)\n");
    kprint("  Physics: Newtonian gravity\n");
    kprint("  Integration: Verlet method\n\n");
    
    while(1) {
        /* Calculate gravitational forces */
        calculate_gravity();
        
        /* Update positions */
        update_positions();
        
        /* Render */
        render_solar_system();
        
        /* Handle input */
        if(key_available()) {
            char key = get_char();
            
            if(key == ' ') {
                paused = !paused;
            }
            else if(key == '+' || key == '=') {
                time_scale *= 2.0;
                if(time_scale > 64.0) time_scale = 64.0;
            }
            else if(key == '-' || key == '_') {
                time_scale /= 2.0;
                if(time_scale < 0.125) time_scale = 0.125;
            }
            else if(key == 'r' || key == 'R') {
                init_solar_system();
            }
            else if(key == 0x1B) { /* ESC */
                kprint("[UNIVERSE] Simulation ended\n");
                return;
            }
        }
        
        /* Small delay to control frame rate */
        sleep(50);
    }
}
